In [327]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

import plotly.express as px
import cufflinks as cf

cf.go_offline()

In [328]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "mysql+pymysql",
    username="root",
    password="Jay@1234",
    host="localhost",
    port=3306,
    database="ecommerce_project"
)

engine = create_engine(connection_url)

In [329]:
import pandas as pd

users = pd.read_sql("select * from users limit 5;", engine)
users

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29

In [330]:
users = pd.read_sql("select * from users;", engine)

products = pd.read_sql("select * from products;", engine)

orders = pd.read_sql("select * from orders;", engine)

order_items = pd.read_sql("select * from order_items;", engine)

reviews = pd.read_sql("select * from reviews;", engine)

events = pd.read_sql("select * from events;", engine)

In [331]:
print(users.shape)
print(products.shape)
print(orders.shape)
print(order_items.shape)
print(reviews.shape)
print(events.shape)

(10000, 6)
(2000, 6)
(20000, 5)
(43525, 7)
(15000, 7)
(80000, 5)

In [332]:
users.head()

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29

In [333]:
users.tail()

,user_id,name,email,gender,city,signup_date
9995,U009996,Jill Moreno,joshua27@example.com,Female,East Monica,2025-05-11
9996,U009997,Cheryl Brown,patrickmoore@example.net,Male,New Kimberlyshire,2024-12-14
9997,U009998,Susan Randolph,bvasquez@example.com,Male,New Kristin,2024-04-17
9998,U009999,Michelle Parker,savannah49@example.net,Female,Wellsfurt,2025-03-15
9999,U010000,Claire Sullivan,thomas24@example.net,Other,East Heather,2024-01-13

In [334]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  str
 1   name         10000 non-null  str
 2   email        10000 non-null  str
 3   gender       10000 non-null  str
 4   city         10000 non-null  str
 5   signup_date  10000 non-null  object
dtypes: object(1), str(5)
memory usage: 1.0+ MB

In [335]:
users.describe(include="all")

,user_id,name,email,gender,city,signup_date
count,10000,10000,10000,10000,10000,10000
unique,10000,9340,10000,3,7755,684
top,U000001,Michael Jones,donaldgarcia@example.net,Other,North Michael,2024-09-12
freq,1,6,1,3419,13,27

In [336]:
users.isnull().sum()

user_id        0
name           0
email          0
gender         0
city           0
signup_date    0
dtype: int64

In [337]:
users.duplicated().sum()

np.int64(0)

In [338]:
users_demo = users.copy()

In [339]:
duplicate_users = users_demo.sample(100, random_state=42)

users_demo = pd.concat(
    [users_demo, duplicate_users],
    ignore_index=True
)

In [340]:
users_demo.duplicated().sum()

np.int64(100)

### remove duplicates in users

In [341]:
users_demo = users_demo.drop_duplicates()

In [342]:
users_demo.duplicated().sum()

np.int64(0)

In [343]:
# First 5 rows
products.head()

  product_id     product_name        category    brand   price  rating
0    P000001         Astra Be        Clothing    Astra  157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech   21.46    3.87
2    P000003     Acme Discuss          Sports     Acme  265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus  541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra  198.00    3.97

In [344]:
# Last 5 rows
products.tail()

     product_id     product_name        category    brand   price  rating
1995    P001996     NeoTech Turn  Home & Kitchen  NeoTech   69.46    4.28
1996    P001997     Zenith Board        Clothing   Zenith  106.67    2.66
1997    P001998  Solace Practice          Beauty   Solace  105.48    4.73
1998    P001999       Willow Old      Automotive   Willow  116.13    2.75
1999    P002000     Harbor Whole           Books   Harbor   64.11    4.17

In [345]:
# Shape
products.shape

(2000, 6)

In [346]:
# Information
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2000 non-null   str
 1   product_name  2000 non-null   str
 2   category      2000 non-null   str
 3   brand         2000 non-null   str
 4   price         2000 non-null   float64
 5   rating        2000 non-null   float64
dtypes: float64(2), str(4)
memory usage: 160.4 KB

In [347]:
# Statistical summary
products.describe(include='all')

       product_id product_name  category   brand        price       rating
count        2000         2000      2000    2000  2000.000000  2000.000000
unique       2000         1848        10      12          NaN          NaN
top       P000001  Pulse Eight  Clothing  Zenith          NaN          NaN
freq            1            3       213     190          NaN          NaN
mean          NaN          NaN       NaN     NaN   200.342230     3.677615
std           NaN          NaN       NaN     NaN   302.742395     0.686478
min           NaN          NaN       NaN     NaN     1.110000     2.500000
25%           NaN          NaN       NaN     NaN    36.335000     3.070000
50%           NaN          NaN       NaN     NaN    84.220000     3.690000
75%           NaN          NaN       NaN     NaN   210.817500     4.250000
max           NaN          NaN       NaN     NaN  2338.130000     4.900000

In [348]:
# Missing values
products.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

In [349]:
products_demo.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

### adding null values in products

In [350]:
# 80 missing product names
products_demo.loc[np.random.choice(products_demo.index, 80, replace=False), "product_name"] = np.nan

# 70 missing brands
products_demo.loc[np.random.choice(products_demo.index, 70, replace=False), "brand"] = np.nan

# 60 missing categories
products_demo.loc[np.random.choice(products_demo.index, 60, replace=False), "category"] = np.nan

# 90 missing prices
products_demo.loc[np.random.choice(products_demo.index, 90, replace=False), "price"] = np.nan

# 75 missing ratings
products_demo.loc[np.random.choice(products_demo.index, 75, replace=False), "rating"] = np.nan

In [351]:
products_demo.isnull().sum()

product_id       0
product_name    80
category        60
brand           70
price           90
rating          75
dtype: int64

In [352]:
# products : 
# Fill missing product names
products_demo["product_name"] = products_demo["product_name"].fillna("Unknown Product")

# Fill missing category
products_demo["category"] = products_demo["category"].fillna(products_demo["category"].mode()[0])

# Fill missing brand
products_demo["brand"] = products_demo["brand"].fillna(products_demo["brand"].mode()[0])

# Fill missing price
products_demo["price"] = products_demo["price"].fillna(products_demo["price"].mean())

# Fill missing rating
products_demo["rating"] = products_demo["rating"].fillna(products_demo["rating"].mean())

In [353]:
products_demo.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

In [354]:
# Duplicate rows
products.duplicated().sum()

np.int64(0)

In [355]:
products_demo = products.copy()

### remove duplicates in products

In [356]:
duplicate_products = products_demo.sample(50, random_state=42)

products_demo = pd.concat(
    [products_demo, duplicate_products],
    ignore_index=True
)

In [357]:
products_demo.duplicated().sum()

np.int64(50)

remove duplicates in products

In [358]:
products_demo = products_demo.drop_duplicates()

In [359]:
products_demo.duplicated().sum()

np.int64(0)

In [360]:
# First 5 rows
orders.head()

    order_id  user_id          order_date order_status  total_amount
0  O00000001  U009310 2025-09-09 14:52:37   processing        689.66
1  O00000002  U003247 2025-04-15 01:18:27    completed       1666.85
2  O00000003  U007252 2025-04-27 15:37:48   processing        665.06
3  O00000004  U008986 2025-10-04 20:35:22    cancelled        689.50
4  O00000005  U008537 2024-11-13 08:15:18    cancelled        860.50

In [361]:
# Last 5 rows
orders.tail()

        order_id  user_id          order_date order_status  total_amount
19995  O00019996  U001139 2024-06-15 19:57:32    completed        268.12
19996  O00019997  U009864 2024-06-20 22:11:58    cancelled        114.74
19997  O00019998  U009525 2024-04-04 21:42:23   processing         21.30
19998  O00019999  U006170 2025-02-27 18:34:29    cancelled        728.97
19999  O00020000  U009938 2025-06-01 08:13:09    cancelled        524.31

In [362]:
# Shape
orders.shape

(20000, 5)

In [363]:
# Data types
orders.dtypes

order_id                   str
user_id                    str
order_date      datetime64[us]
order_status               str
total_amount           float64
dtype: object

In [364]:
# Information
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  str
 1   user_id       20000 non-null  str
 2   order_date    20000 non-null  datetime64[us]
 3   order_status  20000 non-null  str
 4   total_amount  20000 non-null  float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 1.2 MB

In [365]:
# Statistical summary
orders.describe(include='all')

,order_id,user_id,order_date,order_status,total_amount
count,20000,20000,20000,20000,20000.000000
unique,20000,8635,NaN,5,NaN
top,O00000001,U000684,NaN,shipped,NaN
freq,1,10,NaN,4113,NaN
mean,NaN,NaN,2024-12-06 19:27:11.857800,NaN,595.933447
min,NaN,NaN,2024-01-01 00:14:18,NaN,1.110000
25%,NaN,NaN,2024-06-19 04:22:49.500000,NaN,111.355000
50%,NaN,NaN,2024-12-05 10:04:04,NaN,308.195000
75%,NaN,NaN,2025-05-27 04:33:50.500000,NaN,768.195000
max,NaN,NaN,2025-11-14 23:17:26,NaN,7950.740000
std,NaN,NaN,NaN,NaN,776.063336

In [366]:
# Missing values
orders.isnull().sum()

order_id        0
user_id         0
order_date      0
order_status    0
total_amount    0
dtype: int64

In [367]:
users_demo = users.copy()

### adding null values in orders

In [368]:
import numpy as np

np.random.seed(42)

# 150 missing names
users_demo.loc[np.random.choice(users_demo.index, 150, replace=False), "name"] = np.nan

# 120 missing emails
users_demo.loc[np.random.choice(users_demo.index, 120, replace=False), "email"] = np.nan

# 100 missing cities
users_demo.loc[np.random.choice(users_demo.index, 100, replace=False), "city"] = np.nan

# 80 missing genders
users_demo.loc[np.random.choice(users_demo.index, 80, replace=False), "gender"] = np.nan

In [369]:
users_demo.isnull().sum()

user_id          0
name           150
email          120
gender          80
city           100
signup_date      0
dtype: int64

In [370]:
# users :
# Fill missing names
users_demo["name"] = users_demo["name"].fillna("Unknown")

# Fill missing emails
users_demo["email"] = users_demo["email"].fillna("unknown@email.com")

# Fill missing gender with mode
users_demo["gender"] = users_demo["gender"].fillna(users_demo["gender"].mode()[0])

# Fill missing city with mode
users_demo["city"] = users_demo["city"].fillna(users_demo["city"].mode()[0])

In [371]:
# Duplicate rows
orders.duplicated().sum()

np.int64(0)

In [372]:
# First 5 rows
order_items.head()

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
0,I00000001,O00000001,P001758,U009310,2,8.07,16.14
1,I00000002,O00000001,P001119,U009310,1,74.08,74.08
2,I00000003,O00000001,P001794,U009310,1,576.97,576.97
3,I00000004,O00000001,P001038,U009310,1,22.47,22.47
4,I00000005,O00000002,P000859,U003247,1,422.22,422.22

In [373]:
# Last 5 rows
order_items.tail()

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
43520,I00043521,O00019999,P001684,U006170,1,728.97,728.97
43521,I00043522,O00020000,P001940,U009938,3,115.22,345.66
43522,I00043523,O00020000,P000221,U009938,3,22.47,67.41
43523,I00043524,O00020000,P000248,U009938,1,40.54,40.54
43524,I00043525,O00020000,P001340,U009938,1,70.70,70.70

In [374]:
# Shape
order_items.shape

(43525, 7)

In [375]:
# Information
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 43525 entries, 0 to 43524
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  43525 non-null  str
 1   order_id       43525 non-null  str
 2   product_id     43525 non-null  str
 3   user_id        43525 non-null  str
 4   quantity       43525 non-null  int64
 5   item_price     43525 non-null  float64
 6   item_total     43525 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 3.7 MB

In [376]:
# Statistical summary
order_items.describe(include='all')

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
count,43525,43525,43525,43525,43525.000000,43525.000000,43525.000000
unique,43525,20000,2000,8635,NaN,NaN,NaN
top,I00000001,O00000052,P000519,U003319,NaN,NaN,NaN
freq,1,6,38,24,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1.397312,196.636976,273.835013
std,NaN,NaN,NaN,NaN,0.660717,297.259224,471.585104
min,NaN,NaN,NaN,NaN,1.000000,1.110000,1.110000
25%,NaN,NaN,NaN,NaN,1.000000,36.400000,44.590000
50%,NaN,NaN,NaN,NaN,1.000000,83.170000,105.340000
75%,NaN,NaN,NaN,NaN,2.000000,208.050000,274.980000
max,NaN,NaN,NaN,NaN,3.000000,2338.130000,7014.390000

In [377]:
# Missing values
order_items.isnull().sum()

order_item_id    0
order_id         0
product_id       0
user_id          0
quantity         0
item_price       0
item_total       0
dtype: int64

Missing values were intentionally introduced into copies of the Users and Products datasets.Numerical attributes (price, rating) were filled using the mean, while categorical attributes (brand, category, gender, city) were filled using the mode. Missing text fields such as name and product_name were replaced with default placeholder values. After preprocessing, all missing values were successfully removed.

In [378]:
# Duplicate rows
order_items.duplicated().sum()

np.int64(0)

In [379]:
# First 5 rows
reviews.head()

,review_id,order_id,product_id,user_id,rating,review_text,review_date
0,R00000002,O00000001,P001119,U009310,2,Color was different from images.,2024-10-13 03:07:37
1,R00000006,O00000002,P000803,U003247,4,Works perfectly!,2024-06-21 07:11:32
2,R00000008,O00000002,P000454,U003247,4,Item arrived damaged.,2024-05-09 16:41:05
3,R00000011,O00000003,P001030,U007252,5,Highly recommend this brand.,2025-05-10 09:47:38
4,R00000012,O00000004,P000684,U008986,4,Color was different from images.,2024-06-06 07:33:08

In [380]:
# Last 5 rows
reviews.tail()

,review_id,order_id,product_id,user_id,rating,review_text,review_date
14995,R00043509,O00019994,P001043,U006442,3,Decent product for the price.,2025-11-04 22:21:05
14996,R00043514,O00019995,P001959,U005603,3,"Not as expected, quality is poor.",2024-06-14 08:17:26
14997,R00043515,O00019996,P001898,U001139,4,"Not as expected, quality is poor.",2025-04-21 12:44:33
14998,R00043520,O00019998,P001396,U009525,5,Value for money.,2024-07-23 00:55:01
14999,R00043521,O00019999,P001684,U006170,3,Color was different from images.,2024-10-11 17:03:30

In [381]:
# Shape
reviews.shape

(15000, 7)

In [382]:
# Data types
reviews.dtypes

review_id                 str
order_id                  str
product_id                str
user_id                   str
rating                  int64
review_text               str
review_date    datetime64[us]
dtype: object

In [383]:
# Information
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    15000 non-null  str
 1   order_id     15000 non-null  str
 2   product_id   15000 non-null  str
 3   user_id      15000 non-null  str
 4   rating       15000 non-null  int64
 5   review_text  15000 non-null  str
 6   review_date  15000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 1.6 MB

In [384]:
# Statistical summary
reviews.describe(include='all')

,review_id,order_id,product_id,user_id,rating,review_text,review_date
count,15000,15000,15000,15000,15000.000000,15000,15000
unique,15000,11070,1999,6660,NaN,10,NaN
top,R00000002,O00012017,P000497,U009903,NaN,Item arrived damaged.,NaN
freq,1,6,20,11,NaN,1550,NaN
mean,NaN,NaN,NaN,NaN,3.544667,NaN,2024-12-09 07:19:17.304066
min,NaN,NaN,NaN,NaN,1.000000,NaN,2024-01-01 01:23:06
25%,NaN,NaN,NaN,NaN,3.000000,NaN,2024-06-19 05:38:21.500000
50%,NaN,NaN,NaN,NaN,4.000000,NaN,2024-12-10 07:58:32.500000
75%,NaN,NaN,NaN,NaN,4.000000,NaN,2025-05-30 18:46:53.750000
max,NaN,NaN,NaN,NaN,5.000000,NaN,2025-11-14 23:26:42
std,NaN,NaN,NaN,NaN,1.103669,NaN,NaN

In [385]:
# Missing values
reviews.isnull().sum()

review_id      0
order_id       0
product_id     0
user_id        0
rating         0
review_text    0
review_date    0
dtype: int64

In [386]:
# Duplicate rows
reviews.duplicated().sum()

np.int64(0)

In [387]:
# First 5 rows
events.head()

    event_id  user_id product_id event_type     event_timestamp
0  E00000001  U009798    P001393       cart 2025-07-08 14:28:56
1  E00000002  U005881    P000669       view 2025-10-19 23:00:44
2  E00000003  U006348    P001404       view 2025-05-09 07:02:42
3  E00000004  U002664    P000400       cart 2025-07-19 22:47:07
4  E00000005  U005776    P000392       view 2024-10-24 10:20:34

In [388]:
# Last 5 rows
events.tail()

        event_id  user_id product_id event_type     event_timestamp
79995  E00079996  U004661    P001812       cart 2025-03-27 03:44:40
79996  E00079997  U009968    P001291       view 2024-12-27 02:14:17
79997  E00079998  U005926    P001729       view 2025-03-27 18:29:07
79998  E00079999  U005937    P001803       view 2024-05-10 16:29:39
79999  E00080000  U007283    P000084       view 2024-10-22 14:35:56

In [389]:
# Shape
events.shape

(80000, 5)

In [390]:
# Data types
events.dtypes

event_id                      str
user_id                       str
product_id                    str
event_type                    str
event_timestamp    datetime64[us]
dtype: object

In [391]:
# Information
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         80000 non-null  str
 1   user_id          80000 non-null  str
 2   product_id       80000 non-null  str
 3   event_type       80000 non-null  str
 4   event_timestamp  80000 non-null  datetime64[us]
dtypes: datetime64[us](1), str(4)
memory usage: 5.2 MB

In [392]:
# Statistical summary
events.describe(include='all')

         event_id  user_id product_id event_type             event_timestamp
count       80000    80000      80000      80000                       80000
unique      80000     9995       2000          4                         NaN
top     E00000001  U006046    P001112       view                         NaN
freq            1       23         63      56013                         NaN
mean          NaN      NaN        NaN        NaN  2024-12-07 18:36:53.393625
min           NaN      NaN        NaN        NaN         2024-01-01 00:09:40
25%           NaN      NaN        NaN        NaN         2024-06-19 04:59:26
50%           NaN      NaN        NaN        NaN  2024-12-07 11:39:24.500000
75%           NaN      NaN        NaN        NaN  2025-05-28 17:05:37.750000
max           NaN      NaN        NaN        NaN         2025-11-14 23:36:11

In [393]:
# Missing values
events.isnull().sum()

event_id           0
user_id            0
product_id         0
event_type         0
event_timestamp    0
dtype: int64

In [394]:
# Duplicate rows
events.duplicated().sum()

np.int64(0)

# Data Cleaning

After understanding the structure of the dataset, the next step is data cleaning. Data cleaning helps improve data quality by checking data types, converting date columns, removing duplicate records, handling missing values, and preparing the data for exploratory data analysis (EDA).

## Step 1: Check Data Types

First, verify the data type of each column to ensure that every column has the appropriate data type. Date columns should be converted to datetime format before analysis.

In [395]:
users.dtypes

user_id           str
name              str
email             str
gender            str
city              str
signup_date    object
dtype: object

orders.order_date is already datetime.
✅ reviews.review_date is already datetime.
✅ events.event_timestamp is already datetime.
❗ users.signup_date is still an object, so it should be converted to datetime.
✅ All ID columns are strings, which is fine for analysis.

## Step 2: Convert Date Columns

Date columns should be stored in the **datetime** format so they can be used for time-based analysis, such as monthly registrations, revenue trends, and event timelines.

From the data type check, the `signup_date` column in the **users** table is stored as an object and needs to be converted to datetime format.

In [396]:
users["signup_date"] = pd.to_datetime(users["signup_date"])

## Verify the Data Type Conversion

After converting the `signup_date` column, verify that the data type has changed successfully.

In [397]:
users.dtypes

user_id                  str
name                     str
email                    str
gender                   str
city                     str
signup_date    datetime64[s]
dtype: object

In [398]:
products.dtypes

product_id          str
product_name        str
category            str
brand               str
price           float64
rating          float64
dtype: object

### Observation

The **products** dataset has the correct data types. Product information is stored as strings, while the `price` and `rating` columns are stored as numeric values (`float64`), making them suitable for statistical analysis and visualization. No data type conversion is required for this dataset.

## Step 3: Check for Duplicate Records

Duplicate records can lead to inaccurate analysis by counting the same information multiple times. Therefore, each dataset is checked for duplicate rows before performing exploratory data analysis.

In [399]:
print("Users:", users.duplicated().sum())
print("Products:", products.duplicated().sum())
print("Orders:", orders.duplicated().sum())
print("Order Items:", order_items.duplicated().sum())
print("Reviews:", reviews.duplicated().sum())
print("Events:", events.duplicated().sum())

Users: 0
Products: 0
Orders: 0
Order Items: 0
Reviews: 0
Events: 0

### Observation

The duplicate check shows that all six datasets contain **0 duplicate records**. Therefore, no duplicate rows needed to be removed, and the datasets are ready for further preprocessing and analysis.

## Step 4: Check for Missing Values

Missing values can affect the accuracy of data analysis and machine learning models. Therefore, each dataset is checked to identify any null or missing values before proceeding with exploratory data analysis.

In [400]:
print("Users")
print(users.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nOrders")
print(orders.isnull().sum())

Users
user_id        0
name           0
email          0
gender         0
city           0
signup_date    0
dtype: int64

Products
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

Orders
order_id        0
user_id         0
order_date      0
order_status    0
total_amount    0
dtype: int64

In [401]:
print("\nOrder Items")
print(order_items.isnull().sum())

print("\nReviews")
print(reviews.isnull().sum())

print("\nEvents")
print(events.isnull().sum())

Order Items
order_item_id    0
order_id         0
product_id       0
user_id          0
quantity         0
item_price       0
item_total       0
dtype: int64

Reviews
review_id      0
order_id       0
product_id     0
user_id        0
rating         0
review_text    0
review_date    0
dtype: int64

Events
event_id           0
user_id            0
product_id         0
event_type         0
event_timestamp    0
dtype: int64

### Observation

The missing value check confirms that all six datasets contain **no null or missing values**. Since there are no missing records, no imputation or data removal was required. The datasets are complete and ready for exploratory data analysis (EDA).

## Step 5: Check Unique Values

Unique values help us understand the different categories and labels present in the dataset. This step verifies that categorical columns contain expected values before analysis.

In [402]:
print("Gender")
print(users["gender"].unique())

print("\nCategory")
print(products["category"].unique())

print("\nBrand")
print(products["brand"].unique())

print("\nOrder Status")
print(orders["order_status"].unique())

print("\nEvent Type")
print(events["event_type"].unique())

Gender
<ArrowStringArray>
['Other', 'Male', 'Female']
Length: 3, dtype: str

Category
<ArrowStringArray>
[      'Clothing',      'Groceries',         'Sports',    'Electronics',
 'Home & Kitchen',           'Toys',   'Pet Supplies',          'Books',
     'Automotive',         'Beauty']
Length: 10, dtype: str

Brand
<ArrowStringArray>
[    'Astra',   'NeoTech',      'Acme',    'Nimbus',    'Zenith',   'Everest',
    'Harbor',     'Orion', 'GreenLeaf',    'Solace',    'Willow',     'Pulse']
Length: 12, dtype: str

Order Status
<ArrowStringArray>
['processing', 'completed', 'cancelled', 'returned', 'shipped']
Length: 5, dtype: str

Event Type
<ArrowStringArray>
['cart', 'view', 'wishlist', 'purchase']
Length: 4, dtype: str

### Observation

The unique value check confirms that all categorical columns contain valid and meaningful values.

- **Gender** contains three categories: Male, Female, and Other.
- **Category** contains ten product categories.
- **Brand** contains twelve different brands.
- **Order Status** contains five order states: Processing, Completed, Cancelled, Returned, and Shipped.
- **Event Type** contains four user interaction types: View, Cart, Wishlist, and Purchase.

No inconsistent or unexpected categorical values were found. Therefore, no additional cleaning was required.

# Data Cleaning Summary

The data cleaning process was performed to ensure the quality and consistency of the datasets before analysis.

### Data Cleaning Performed

- Verified the data types of all columns.
- Converted the `signup_date` column to datetime format.
- Confirmed that all other date columns were already stored as datetime.
- Checked for duplicate records in all six datasets.
- Verified that no duplicate records were present,and i have added and removed.
- Checked for missing values in all datasets,and i have added for myself.
- Confirmed that no missing values were present.
- Validated categorical columns using unique value checks.

### Conclusion

The datasets are clean, consistent, and ready for Exploratory Data Analysis (EDA).

# Exploratory Data Analysis (EDA)

Exploratory Data Analysis (EDA) is performed to understand the structure of the e-commerce data, identify patterns, analyze customer behavior, evaluate product performance, and generate business insights.

### Total Number of Users

The first step is to determine the total number of registered users in the e-commerce platform. This provides an overview of the customer base available for analysis.

In [403]:
# Total number of users
users.shape[0]

10000

### Observation

The dataset contains **10,000 registered users**. This indicates that the dataset is sufficiently large for performing customer behavior analysis, demographic analysis, and recommendation-based insights.

### Gender Distribution

This analysis shows the distribution of users based on gender. Understanding the gender distribution helps identify the composition of the customer base and can support targeted marketing and personalization strategies.

In [404]:
# Gender distribution
users["gender"].value_counts()

gender
Other     3419
Female    3334
Male      3247
Name: count, dtype: int64

### Observation

The dataset contains users from three gender categories:

- **Other:** 3,419 users
- **Female:** 3,334 users
- **Male:** 3,247 users

The distribution is relatively balanced across all three categories, with no single gender dominating the dataset.

### Business Insight

Since the customer base is evenly distributed across different gender categories, the e-commerce platform can design inclusive marketing campaigns and personalized product recommendations without heavily focusing on a single gender group.

### Top 10 Cities by Number of Users

This analysis identifies the cities with the highest number of registered users. Understanding the geographic distribution of customers helps businesses identify major markets and target locations for promotions, marketing campaigns, and inventory planning.

In [405]:
# Top 10 cities
users["city"].value_counts().head(10)

city
North Michael    13
West Michelle    11
Michaelmouth     10
Port Kimberly     9
Lake John         9
New Michael       9
West Jennifer     9
West Michael      9
East David        9
East Michael      9
Name: count, dtype: int64

### Observation

The analysis shows that user registrations are spread across many different cities. The city **North Michael** has the highest number of registered users (13), followed by **West Michelle** (11) and **Michaelmouth** (10). The remaining cities in the top 10 have between 9 and 10 registered users.

The distribution indicates that the customer base is geographically diverse, with no single city having a significantly higher number of users than the others.

### Business Insight

Since users are distributed across multiple cities, the e-commerce platform has a broad customer base rather than relying on a single location. Marketing campaigns, promotional offers, and inventory planning can be customized for different cities to improve customer engagement and sales.

### Monthly User Registrations

This analysis examines the number of users who registered in each month. It helps identify seasonal trends, customer growth patterns, and periods of increased user acquisition.

In [406]:
# Monthly user registrations
users.groupby(users["signup_date"].dt.month).size()

signup_date
1     900
2     892
3     972
4     861
5     868
6     851
7     844
8     886
9     892
10    904
11    677
12    453
dtype: int64

### Observation

The monthly registration analysis shows that user registrations are fairly consistent throughout most of the year.

- **March** recorded the highest number of registrations (**972 users**).
- **October** (**904**) and **January** (**900**) also had relatively high registrations.
- Registration numbers gradually decreased towards the end of the year.
- **December** had the lowest number of registrations (**453 users**).

Overall, there is no extreme variation in registrations during the first ten months, but a noticeable decline is observed in November and December.

### Business Insight

The decline in user registrations during the last two months may indicate seasonal trends or reduced customer acquisition during that period. The business can introduce promotional campaigns, holiday discounts, referral programs, or targeted advertisements during November and December to attract more new users and maintain steady customer growth throughout the year.

# 2. Products Analysis

The products dataset contains information about the items available on the e-commerce platform, including category, brand, price, and customer rating. Analyzing this dataset helps identify product diversity, pricing trends, brand performance, and customer preferences.

### Total Number of Products

This analysis determines the total number of products available in the e-commerce platform.

In [407]:
# Total number of products
products.shape[0]

2000

### Observation

The e-commerce dataset contains **2,000 products**. This indicates that the platform offers a diverse product catalog, providing customers with a wide range of shopping options across different categories and brands.

### Business Insight

A product catalog containing 2,000 products provides sufficient variety for customer analysis, recommendation systems, and inventory management. The large number of products also enables the business to study customer preferences across multiple categories and brands.

### Products by Category

This analysis examines the number of products available in each product category. It helps identify which categories have the largest product offerings and provides insights into the overall product distribution.

In [408]:
# Products by category
products["category"].value_counts()

category
Clothing          213
Toys              213
Pet Supplies      212
Beauty            207
Electronics       203
Home & Kitchen    199
Books             194
Automotive        193
Groceries         183
Sports            183
Name: count, dtype: int64

### Observation

The dataset contains **10 product categories** with a fairly balanced distribution of products.

- **Clothing** and **Toys** have the highest number of products (**213** each).
- **Pet Supplies** follows closely with **212** products.
- **Beauty** (207) and **Electronics** (203) also have a large product selection.
- **Groceries** and **Sports** have the fewest products (**183** each).

Overall, the difference in product count between categories is relatively small, indicating that the product catalog is well distributed across different categories.

### Business Insight

A balanced product distribution ensures that customers have a wide variety of choices across multiple categories. Since no single category dominates the catalog, the business can promote different categories equally and use customer purchase behavior to identify high-performing categories for future inventory planning.

### Products by Brand

This analysis examines the number of products available under each brand. Understanding the brand distribution helps identify the diversity of brands offered on the platform and supports brand performance analysis.

In [409]:
# Products by brand
products["brand"].value_counts()

brand
Zenith       190
Harbor       183
Nimbus       182
GreenLeaf    174
Astra        165
Willow       165
NeoTech      163
Orion        163
Everest      157
Solace       156
Acme         155
Pulse        147
Name: count, dtype: int64

### Observation

The dataset contains **12 different brands**. The product distribution across brands is relatively balanced.

- **Zenith** has the highest number of products (**190**).
- **Harbor** (**183**) and **Nimbus** (**182**) also have a large product catalog.
- **Pulse** has the fewest products (**147**).

Overall, the difference in product count between brands is relatively small, indicating that the product catalog is evenly distributed across multiple brands.

### Business Insight

The balanced distribution of products across brands provides customers with a wide range of choices. Brands with larger product catalogs, such as Zenith and Harbor, may contribute more to sales, while brands with fewer products may require additional promotions or product expansion to improve their market presence.

### Visualization: Products by Brand

The following bar chart illustrates the number of products available for each brand.

In [410]:
import plotly.express as px

brand_counts = products["brand"].value_counts().reset_index()
brand_counts.columns = ["Brand", "Count"]

fig = px.bar(
    brand_counts,
    x="Brand",
    y="Count",
    title="Products by Brand"
)

fig.show()

### Average Product Price

This analysis calculates the average price of all products available on the e-commerce platform. It provides an overview of the general pricing level of the product catalog.

In [411]:
# Average product price
products["price"].mean()

np.float64(200.34223)

### Observation

The average price of products in the dataset is **$200.34**. This indicates that the overall product catalog is moderately priced, although individual product prices may vary across different categories and brands.

### Business Insight

Understanding the average product price helps the business evaluate its pricing strategy. This metric can also be used to compare pricing across brands and categories, identify premium products, and support future pricing decisions.

### Product Price Statistics

This analysis provides summary statistics for product prices, including the minimum, maximum, median, quartiles, and standard deviation. These statistics help us understand the distribution and spread of product prices.

In [412]:
products["price"].describe()

count    2000.000000
mean      200.342230
std       302.742395
min         1.110000
25%        36.335000
50%        84.220000
75%       210.817500
max      2338.130000
Name: price, dtype: float64

### Observation

The summary statistics show that product prices vary considerably across the catalog.

- The **average product price** is **$200.34**.
- The **minimum price** is **$1.11**.
- The **maximum price** is **$2,338.13**.
- **50%** of the products are priced below **$84.22** (median).
- **75%** of the products cost less than **$210.82**.

The large difference between the mean ($200.34) and the median ($84.22), along with a high standard deviation ($302.74), suggests that a small number of expensive products increase the overall average price.

### Business Insight

The product catalog contains a wide price range, allowing the business to serve customers with different budgets. Since the average price is much higher than the median price, premium-priced products may contribute significantly to overall revenue even though many products are sold at lower prices.

### Visualization: Product Price Distribution

The following histogram shows how product prices are distributed across the catalog. It helps identify whether most products are low-priced, medium-priced, or high-priced.

In [413]:
import plotly.express as px

fig = px.histogram(
    products,
    x="price",
    nbins=30,
    title="Distribution of Product Prices"
)

fig.show()

### Top 10 Most Expensive Products

This analysis identifies the ten most expensive products in the dataset. These products may represent premium items that contribute significantly to the platform's revenue.

In [414]:
products.sort_values(
    by="price",
    ascending=False
).head(10)

     product_id    product_name     category   brand    price  rating
1023    P001024      Astra Pull  Electronics   Astra  2338.13    3.47
909     P000910     Orion Group  Electronics   Orion  2337.85    3.44
135     P000136    Zenith Phone  Electronics  Zenith  2169.98    4.38
1526    P001527   Willow Result  Electronics  Willow  2035.42    3.87
1374    P001375     Astra Owner  Electronics   Astra  1993.95    2.52
1182    P001183     Nimbus Word  Electronics  Nimbus  1835.32    3.51
641     P000642      Acme Group  Electronics    Acme  1816.28    3.65
1743    P001744     Acme Artist  Electronics    Acme  1797.55    3.21
20      P000021  Willow Special  Electronics  Willow  1772.36    2.90
680     P000681       Acme Keep  Electronics    Acme  1708.20    2.93

### Observation

The top 10 most expensive products are all priced above **$1,700**, with the highest-priced product costing **$2,338.13**.

Interestingly, **all ten products belong to the Electronics category**, indicating that electronic products are the premium offerings in this dataset. Brands such as **Astra**, **Acme**, **Willow**, **Orion**, **Nimbus**, and **Zenith** appear multiple times among the most expensive products.

Customer ratings for these products range from **2.52 to 4.38**, suggesting that higher prices do not necessarily correspond to higher customer ratings.

### Business Insight

The Electronics category contains the platform's highest-priced products, making it a major contributor to potential revenue. However, some premium-priced products have relatively low customer ratings, indicating opportunities to improve product quality, customer satisfaction, or pricing strategies. Monitoring customer feedback for these products can help increase sales and improve the overall customer experience.

### Visualization: Top 10 Most Expensive Products

The following bar chart displays the ten most expensive products available on the e-commerce platform.

In [415]:
import plotly.express as px

top10 = products.sort_values(
    by="price",
    ascending=False
).head(10)

fig = px.bar(
    top10,
    x="product_name",
    y="price",
    color="brand",
    title="Top 10 Most Expensive Products"
)

fig.show()

### Top 10 Highest Rated Products

This analysis identifies the ten highest-rated products based on customer ratings. It helps understand which products have received the best customer feedback.

In [416]:
products.sort_values(
    by="rating",
    ascending=False
).head(10)

     product_id       product_name     category      brand   price  rating
370     P000371      NeoTech Stand    Groceries    NeoTech   19.06    4.90
607     P000608    GreenLeaf Visit         Toys  GreenLeaf   42.74    4.89
290     P000291        Nimbus Goal        Books     Nimbus   50.30    4.89
1164    P001165       Willow Never    Groceries     Willow   12.97    4.89
690     P000691  GreenLeaf Concern    Groceries  GreenLeaf    3.96    4.89
483     P000484     Everest Almost       Beauty    Everest  104.34    4.89
191     P000192         Pulse Near  Electronics      Pulse  455.43    4.88
94      P000095  NeoTech Certainly     Clothing    NeoTech  121.02    4.88
1954    P001955       Astra Remain       Beauty      Astra  124.68    4.88
668     P000669      Acme Personal         Toys       Acme   36.42    4.88

### Observation

The highest-rated products have customer ratings ranging from **4.88 to 4.90**.

These products belong to different categories, including:

- Groceries
- Toys
- Books
- Beauty
- Electronics
- Clothing

The prices of these products vary significantly, from **$3.96** to **$455.43**. This indicates that highly rated products are not necessarily the most expensive products.

### Business Insight

Customer satisfaction is not solely determined by product price. Several low-cost products have excellent ratings, suggesting that product quality, value for money, and customer experience play an important role in customer satisfaction.

The business can recommend highly rated products to customers and feature them in promotional campaigns to increase customer trust and sales.

### Visualization: Top 10 Highest Rated Products

The following bar chart displays the highest-rated products available on the e-commerce platform.

In [417]:
import plotly.express as px

top_rated = products.sort_values(
    by="rating",
    ascending=False
).head(10)

fig = px.bar(
    top_rated,
    x="product_name",
    y="rating",
    color="category",
    title="Top 10 Highest Rated Products"
)

fig.show()

# 3. Orders Analysis

The orders dataset contains transaction information, including order dates, order status, and total order amounts. Analyzing this data helps understand sales performance, revenue trends, and customer purchasing behavior.

### Total Number of Orders

This analysis determines the total number of orders placed on the e-commerce platform.

In [418]:
# Total number of orders
orders.shape[0]

20000

### Observation

The dataset contains **20,000 orders**, indicating a high volume of customer transactions. This provides sufficient data to analyze sales trends, customer purchasing behavior, and order performance.

### Business Insight

A large number of orders enables the business to identify purchasing patterns, evaluate sales performance, and generate meaningful insights that can support inventory management, marketing strategies, and customer retention.

### Total Revenue

This analysis calculates the total revenue generated from all completed orders in the dataset. It provides an overall measure of the platform's sales performance.

In [419]:
# Total revenue
orders["total_amount"].sum()

np.float64(11918668.95)

### Observation

The e-commerce platform generated a **total revenue of $11,918,668.95** from **20,000 orders**. This indicates a high level of sales activity within the dataset and provides a strong foundation for analyzing customer purchasing behavior and revenue trends.

### Business Insight

The total revenue reflects the overall sales performance of the business. This metric can be monitored over time to evaluate business growth, measure the impact of marketing campaigns, and identify opportunities to increase sales through customer engagement and product recommendations.

### Average Order Value

Average Order Value (AOV) represents the average amount spent per order. It is an important metric for understanding customer purchasing behavior and evaluating the effectiveness of pricing and promotional strategies.

In [420]:
# Average Order Value
orders["total_amount"].mean()

np.float64(595.9334474999999)

### Observation

The **Average Order Value (AOV)** is **$595.93**. This means that, on average, customers spend approximately **$596** per order on the e-commerce platform.

### Business Insight

The Average Order Value helps measure customer spending habits. Increasing the AOV through product bundles, cross-selling, upselling, and personalized recommendations can significantly increase total revenue without necessarily increasing the number of customers.

### Order Status Distribution

This analysis examines the number of orders in each order status. Understanding the distribution of order statuses helps evaluate the efficiency of the order fulfillment process and identify potential issues such as cancellations or returns.

In [421]:
# Order status distribution
orders["order_status"].value_counts()

order_status
shipped       4113
returned      4066
completed     4021
cancelled     3920
processing    3880
Name: count, dtype: int64

### Observation

The order status distribution is fairly balanced across all five categories.

- **Shipped:** 4,113 orders
- **Returned:** 4,066 orders
- **Completed:** 4,021 orders
- **Cancelled:** 3,920 orders
- **Processing:** 3,880 orders

The number of orders in each status is relatively similar, with shipped orders being the highest and processing orders being the lowest.

### Visualization: Order Status Distribution

The following bar chart shows the number of orders in each order status.

In [422]:
import plotly.express as px

status_counts = orders["order_status"].value_counts().reset_index()
status_counts.columns = ["Order Status", "Count"]

fig = px.bar(
    status_counts,
    x="Order Status",
    y="Count",
    color="Order Status",
    title="Order Status Distribution"
)

fig.show()

### Monthly Orders

This analysis calculates the number of orders placed in each month. It helps identify seasonal purchasing patterns and changes in customer order volume throughout the year.

In [423]:
# Monthly orders
orders.groupby(
    orders["order_date"].dt.month
).size()

order_date
1     1767
2     1639
3     1835
4     1791
5     1810
6     1765
7     1854
8     1807
9     1788
10    1792
11    1264
12     888
dtype: int64

### Observation

The monthly order analysis shows that order volumes remain relatively consistent throughout most of the year.

- **July** recorded the highest number of orders (**1,854**).
- **March** (**1,835**) and **May** (**1,810**) also experienced high order volumes.
- The number of orders decreases noticeably during the last two months of the year.
- **December** recorded the lowest number of orders (**888**).

Overall, customer purchasing activity is stable for most
 of the year, with a significant decline observed in November and December.

### Visualization: Monthly Orders

The following line chart illustrates the number of orders placed each month, making it easier to identify trends and seasonal patterns.

In [424]:
import plotly.express as px

monthly_orders = (
    orders.groupby(orders["order_date"].dt.month)
    .size()
    .reset_index(name="Orders")
)

monthly_orders.columns = ["Month", "Orders"]

fig = px.line(
    monthly_orders,
    x="Month",
    y="Orders",
    markers=True,
    title="Monthly Orders"
)

fig.show()

### Monthly Revenue

This analysis calculates the total revenue generated in each month. It helps identify sales trends, seasonal revenue patterns, and periods of strong or weak business performance.

In [425]:
# Monthly revenue
orders.groupby(
    orders["order_date"].dt.month
)["total_amount"].sum()

order_date
1     1046038.87
2      974090.97
3     1046877.95
4     1077469.41
5     1091377.77
6     1056448.28
7     1137336.74
8     1031340.01
9     1051443.49
10    1050549.94
11     789393.85
12     566301.67
Name: total_amount, dtype: float64

### Observation

The monthly revenue analysis shows that revenue remains relatively stable throughout most of the year.

- **July** generated the highest revenue (**$1,137,336.74**).
- **May** (**$1,091,377.77**) and **April** (**$1,077,469.41**) also recorded strong sales.
- Revenue declined significantly during **November** (**$789,393.85**) and **December** (**$566,301.67**).
- **December** generated the lowest monthly revenue.

Overall, the revenue trend closely follows the monthly order trend, indicating that higher order volumes generally result in higher revenue.

### Business Insight

The decrease in revenue during the last two months of the year suggests an opportunity for the business to improve sales through seasonal promotions, personalized recommendations, loyalty rewards, and targeted marketing campaigns. Monitoring monthly revenue trends helps evaluate business performance and plan future sales strategies.

### Visualization: Monthly Revenue

The following line chart displays the total revenue generated in each month and highlights the overall sales trend.

In [426]:
import plotly.express as px

monthly_revenue = (
    orders.groupby(orders["order_date"].dt.month)["total_amount"]
    .sum()
    .reset_index(name="Revenue")
)

monthly_revenue.columns = ["Month", "Revenue"]

fig = px.line(
    monthly_revenue,
    x="Month",
    y="Revenue",
    markers=True,
    title="Monthly Revenue"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue ($)"
)

fig.show()

### 4. Reviews Analysis

The reviews dataset contains customer ratings and review comments for purchased products. This analysis helps evaluate customer satisfaction and identify products that receive positive or negative feedback.

### Total Number of Reviews

This analysis determines the total number of customer reviews available in the dataset.

In [427]:
# Total number of reviews
reviews.shape[0]

15000

### Observation

The dataset contains **15,000 customer reviews**. This provides a substantial amount of customer feedback that can be used to analyze product satisfaction, identify highly rated products, and understand customer opinions.

### Business Insight

A large number of customer reviews allows the business to better understand customer preferences and satisfaction. Review data can also be used for sentiment analysis, product recommendations, and identifying products that require quality improvements.

### Average Customer Rating

This analysis calculates the average rating given by customers. It provides an overall measure of customer satisfaction across all reviewed products.

In [428]:
# Average customer rating
reviews["rating"].mean()

np.float64(3.5446666666666666)

### Observation

The average customer rating is **3.54 out of 5**. This indicates that customer satisfaction is moderate, with most products receiving average to good ratings.

### Business Insight

An average rating of 3.54 suggests that customers are generally satisfied with their purchases. However, there is still an opportunity to improve product quality and customer experience to increase ratings and encourage repeat purchases.

### Rating Distribution

This analysis shows how customer ratings are distributed across the five rating levels. It helps understand the overall pattern of customer feedback.

In [429]:
reviews["rating"].value_counts().sort_index()

rating
1     594
2    2084
3    4289
4    4624
5    3409
Name: count, dtype: int64

### Observation

The customer rating distribution is as follows:

- **1 Star:** 594 reviews
- **2 Stars:** 2,084 reviews
- **3 Stars:** 4,289 reviews
- **4 Stars:** 4,624 reviews
- **5 Stars:** 3,409 reviews

Most customer reviews are **4-star and 5-star ratings**, while very few customers gave 1-star ratings. This indicates that customers are generally satisfied with the products available on the platform.

### Business Insight

The high number of 4-star and 5-star reviews suggests that most customers have a positive shopping experience. Products with lower ratings should be analyzed further to identify issues related to quality, pricing, or customer expectations. Improving these products could lead to higher customer satisfaction and increased repeat purchases.

### Visualization: Rating Distribution

The following bar chart illustrates the distribution of customer ratings across all reviews.

In [430]:
import plotly.express as px

rating_counts = reviews["rating"].value_counts().sort_index().reset_index()
rating_counts.columns = ["Rating", "Count"]

fig = px.bar(
    rating_counts,
    x="Rating",
    y="Count",
    title="Customer Rating Distribution",
    color="Rating",
    text="Count"
)

fig.update_layout(
    xaxis_title="Rating",
    yaxis_title="Number of Reviews"
)

fig.show()

### Most Reviewed Products

This analysis identifies the products that have received the highest number of customer reviews. Products with more reviews are generally more popular or have been purchased more frequently.

In [431]:
# Top 10 most reviewed products
reviews["product_id"].value_counts().head(10)

product_id
P000497    20
P001387    18
P001055    18
P000902    17
P000762    17
P000233    16
P000178    16
P001036    16
P000448    16
P001925    16
Name: count, dtype: int64

### Observation

The top reviewed products received between **16 and 20 customer reviews**.

The most reviewed products are:

| Product ID | Number of Reviews |
|------------|------------------:|
| P000497 | 20 |
| P001387 | 18 |
| P001055 | 18 |
| P000902 | 17 |
| P000762 | 17 |
| P000233 | 16 |
| P000178 | 16 |
| P001036 | 16 |
| P000448 | 16 |
| P001925 | 16 |

The difference in review counts among the top products is relatively small, indicating that customer reviews are fairly evenly distributed across products.

### Business Insight

Products with a higher number of reviews generally receive greater customer attention and engagement. These products can be highlighted in recommendation sections or promotional campaigns to encourage additional purchases. Products with very few reviews could be targeted with review request emails after purchase to increase customer feedback.

### Visualization: Most Reviewed Products

The following bar chart displays the products that received the highest number of customer reviews.

In [432]:
import plotly.express as px

top_reviewed = reviews["product_id"].value_counts().head(10).reset_index()
top_reviewed.columns = ["Product ID", "Number of Reviews"]

fig = px.bar(
    top_reviewed,
    x="Product ID",
    y="Number of Reviews",
    title="Top 10 Most Reviewed Products",
    text="Number of Reviews"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Reviews"
)

fig.show()

### Highest Rated Products

This analysis calculates the average customer rating for each product and identifies the products with the highest average ratings.

In [433]:
# Top 10 highest rated products
reviews.groupby("product_id")["rating"].mean().sort_values(ascending=False).head(10)

product_id
P000773    5.000000
P001986    5.000000
P000844    5.000000
P000833    5.000000
P000275    5.000000
P000904    5.000000
P001074    4.750000
P001931    4.750000
P001455    4.666667
P000060    4.666667
Name: rating, dtype: float64

### Observation

Several products achieved an average customer rating of **5.0**, indicating that customers who reviewed these products were highly satisfied.

The highest-rated products include:

| Product ID | Average Rating |
|------------|---------------:|
| P000773 | 5.00 |
| P001986 | 5.00 |
| P000844 | 5.00 |
| P000833 | 5.00 |
| P000275 | 5.00 |
| P000904 | 5.00 |
| P001074 | 4.75 |
| P001931 | 4.75 |
| P001455 | 4.67 |
| P000060 | 4.67 |

These products received the highest average ratings among all reviewed products.

### Business Insight

Products with high customer ratings indicate strong customer satisfaction and can be featured in recommendation systems, promotional campaigns, and "Top Rated Products" sections. However, the number of reviews should also be considered, since products with only a few reviews may have perfect ratings that are not yet representative of overall customer opinion.

### Visualization: Highest Rated Products

The following bar chart displays the products with the highest average customer ratings.

In [434]:
import plotly.express as px

top_rated = (
    reviews.groupby("product_id")["rating"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_rated.columns = ["Product ID", "Average Rating"]

fig = px.bar(
    top_rated,
    x="Product ID",
    y="Average Rating",
    title="Top 10 Highest Rated Products",
    text="Average Rating"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Average Rating"
)

fig.show()

### Monthly Reviews

This analysis calculates the number of customer reviews submitted each month. It helps identify periods with higher or lower customer engagement.

In [435]:
# Monthly reviews
reviews.groupby(
    reviews["review_date"].dt.month
).size()

review_date
1     1351
2     1251
3     1363
4     1338
5     1316
6     1327
7     1386
8     1298
9     1346
10    1359
11     972
12     693
dtype: int64

# 5. Events Analysis

The events dataset records user interactions with products on the e-commerce platform. These interactions include viewing products, adding products to the cart, adding products to the wishlist, and purchasing products.

Analyzing user events helps understand customer behavior before making a purchase and identifies products with the highest engagement.

### Total Number of Events

This analysis determines the total number of user interaction events recorded in the dataset.

In [436]:
# Total number of events
events.shape[0]

80000

### Observation

The dataset contains **80,000 user interaction events**. These events capture customer behavior throughout the shopping journey and provide valuable information about how users interact with products before making purchasing decisions.

### Business Insight

A large number of user interaction events provides valuable behavioral data that can be used to understand customer preferences, improve product recommendations, optimize marketing strategies, and increase conversion rates. Event data helps businesses identify which products receive the most attention and where customers drop off before completing a purchase.

### Event Type Distribution

This analysis calculates the frequency of each type of user interaction recorded in the dataset, including product views, cart additions, wishlist additions, and purchases.

In [437]:
# Event type distribution
events["event_type"].value_counts()

event_type
view        56013
cart        12035
wishlist     7946
purchase     4006
Name: count, dtype: int64

### Observation

The distribution of user events is as follows:

| Event Type | Count |
|------------|------:|
| View | 56,013 |
| Cart | 12,035 |
| Wishlist | 7,946 |
| Purchase | 4,006 |

Product **views** account for the majority of user interactions, while **purchase** events represent the smallest proportion. This indicates that many users browse products, but only a smaller percentage complete a purchase.

### Business Insight

The large number of product views compared to purchases suggests a conversion gap in the customer journey. The business can improve conversion rates by implementing personalized recommendations, targeted promotions, discount offers, simplified checkout processes, and cart reminder notifications. Analyzing customer behavior between the view, cart, wishlist, and purchase stages can help identify opportunities to increase sales.

### Visualization: Event Type Distribution

The following bar chart displays the frequency of each user interaction event on the e-commerce platform.

In [438]:
import plotly.express as px

event_counts = events["event_type"].value_counts().reset_index()
event_counts.columns = ["Event Type", "Count"]

fig = px.bar(
    event_counts,
    x="Event Type",
    y="Count",
    color="Event Type",
    text="Count",
    title="Event Type Distribution"
)

fig.update_layout(
    xaxis_title="Event Type",
    yaxis_title="Number of Events"
)

fig.show()

### Monthly User Activity

This analysis calculates the number of user interaction events recorded each month. It helps identify trends in customer engagement throughout the year.

In [439]:
# Monthly user activity
events.groupby(
    events["event_timestamp"].dt.month
).size()

event_timestamp
1     7206
2     6626
3     7194
4     7129
5     7215
6     6922
7     7359
8     7346
9     7058
10    7217
11    5133
12    3595
dtype: int64

### Observation

The monthly distribution of user interaction events is relatively consistent throughout most of the year.

| Month | Events |
|------:|-------:|
| January | 7,206 |
| February | 6,626 |
| March | 7,194 |
| April | 7,129 |
| May | 7,215 |
| June | 6,922 |
| July | **7,359** |
| August | 7,346 |
| September | 7,058 |
| October | 7,217 |
| November | 5,133 |
| December | **3,595** |

- **July** recorded the highest customer activity with **7,359 events**.
- **August** and **October** also showed high engagement.
- Customer activity declined significantly during **November** and **December**.
- **December** recorded the lowest number of user events.

### Business Insight

Customer engagement remains stable throughout most of the year but declines during the last two months. Businesses can increase customer engagement during these periods by offering seasonal promotions, personalized recommendations, festive discounts, and targeted marketing campaigns to encourage users to browse and purchase more products.

### Visualization: Monthly User Activity

The following line chart illustrates the number of user interaction events recorded each month.

In [440]:
import plotly.express as px

monthly_events = (
    events.groupby(events["event_timestamp"].dt.month)
    .size()
    .reset_index(name="Events")
)

monthly_events.columns = ["Month", "Events"]

fig = px.line(
    monthly_events,
    x="Month",
    y="Events",
    markers=True,
    title="Monthly User Activity"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Number of Events"
)

fig.show()

### Most Viewed Products

This analysis identifies the products that customers viewed most frequently. Highly viewed products indicate strong customer interest and can help identify popular products.

In [441]:
# Top 10 most viewed products
events[
    events["event_type"] == "view"
]["product_id"].value_counts().head(10)

product_id
P000516    46
P000101    42
P001193    42
P001771    42
P001832    42
P001435    42
P001942    42
P000608    42
P000591    41
P000589    41
Name: count, dtype: int64

### Observation

The most frequently viewed products are listed below:

| Product ID | Number of Views |
|------------|----------------:|
| P000516 | 46 |
| P000101 | 42 |
| P001193 | 42 |
| P001771 | 42 |
| P001832 | 42 |
| P001435 | 42 |
| P001942 | 42 |
| P000608 | 42 |
| P000591 | 41 |
| P000589 | 41 |

The highest viewed product (**P000516**) received **46 views**, while the remaining top products received between **41 and 42 views**. The view counts are relatively close, indicating customer interest is distributed across multiple products rather than concentrated on a single product.

### Business Insight

Products with high view counts attract significant customer attention and should be highlighted in marketing campaigns or recommendation sections. However, businesses should compare product views with purchase data to determine whether customer interest is successfully converted into sales. Products with many views but few purchases may require pricing adjustments, improved descriptions, or promotional offers.

### Visualization: Most Viewed Products

The following bar chart displays the ten most viewed products based on user interaction events.

In [442]:
import plotly.express as px

top_viewed = (
    events[
        events["event_type"] == "view"
    ]["product_id"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_viewed.columns = ["Product ID", "Views"]

fig = px.bar(
    top_viewed,
    x="Product ID",
    y="Views",
    text="Views",
    title="Top 10 Most Viewed Products"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Number of Views"
)

fig.show()

### Most Added-to-Cart Products

This analysis identifies the products that customers added to their shopping carts most frequently. Products with high cart counts indicate strong purchase intent.

In [443]:
# Top 10 most added-to-cart products
events[
    events["event_type"] == "cart"
]["product_id"].value_counts().head(10)

product_id
P001938    17
P001112    16
P001086    16
P000604    16
P000967    16
P000233    16
P001689    15
P001815    15
P001651    15
P000268    15
Name: count, dtype: int64

### Observation

The top 10 most added-to-cart products are shown below:

| Product ID | Cart Count |
|------------|-----------:|
| P001938 | 17 |
| P001112 | 16 |
| P001086 | 16 |
| P000604 | 16 |
| P000967 | 16 |
| P000233 | 16 |
| P001689 | 15 |
| P001815 | 15 |
| P001651 | 15 |
| P000268 | 15 |

The product **P001938** was added to customers' shopping carts **17 times**, while the remaining top products were added between **15 and 16 times**.

### Business Insight

Products with high cart activity demonstrate strong customer purchase intent. Businesses can improve conversions by ensuring these products remain in stock, offering personalized cart reminders, and providing promotional discounts to encourage customers to complete their purchases.

### Visualization: Most Added-to-Cart Products

The following bar chart displays the top 10 products that customers added to their shopping carts.

In [444]:
import plotly.express as px

top_cart = (
    events[
        events["event_type"] == "cart"
    ]["product_id"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_cart.columns = ["Product ID", "Cart Count"]

fig = px.bar(
    top_cart,
    x="Product ID",
    y="Cart Count",
    text="Cart Count",
    title="Top 10 Most Added-to-Cart Products"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Number of Cart Additions"
)

fig.show()

### Most Wishlisted Products

This analysis identifies the products that customers added to their wishlists most frequently. Wishlist activity indicates products that customers are interested in purchasing in the future.

In [445]:
# Top 10 most wishlisted products
events[
    events["event_type"] == "wishlist"
]["product_id"].value_counts().head(10)

product_id
P001361    11
P001775    11
P001464    10
P001633    10
P001959    10
P000084    10
P001989    10
P000221    10
P000243    10
P000808    10
Name: count, dtype: int64

### Observation

The top 10 most wishlisted products are listed below:

| Product ID | Wishlist Count |
|------------|---------------:|
| P001361 | 11 |
| P001775 | 11 |
| P001464 | 10 |
| P001633 | 10 |
| P001959 | 10 |
| P000084 | 10 |
| P001989 | 10 |
| P000221 | 10 |
| P000243 | 10 |
| P000808 | 10 |

Products **P001361** and **P001775** were added to customers' wishlists **11 times**, while the remaining top products were added **10 times** each. Wishlist activity is fairly evenly distributed among these products.

### Business Insight

Products that appear frequently in customers' wishlists indicate future purchase intent. The business can encourage conversions by sending price-drop notifications, wishlist reminders, personalized recommendations, or limited-time promotional offers for these products.

### Visualization: Most Wishlisted Products

The following bar chart displays the top 10 products that customers added to their wishlists.

In [446]:
import plotly.express as px

top_wishlist = (
    events[
        events["event_type"] == "wishlist"
    ]["product_id"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_wishlist.columns = ["Product ID", "Wishlist Count"]

fig = px.bar(
    top_wishlist,
    x="Product ID",
    y="Wishlist Count",
    text="Wishlist Count",
    title="Top 10 Most Wishlisted Products"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Number of Wishlist Additions"
)

fig.show()

### Most Purchased Products

This analysis identifies the products that customers purchased most frequently based on purchase events. These products represent the highest-performing items in terms of completed purchase interactions.

In [447]:
# Top 10 most purchased products
events[
    events["event_type"] == "purchase"
]["product_id"].value_counts().head(10)

product_id
P001113    8
P000984    8
P000454    7
P000258    7
P000510    7
P001011    7
P001235    7
P001936    6
P001647    6
P000560    6
Name: count, dtype: int64

### Observation

The top 10 most purchased products are listed below:

| Product ID | Purchase Count |
|------------|---------------:|
| P001113 | 8 |
| P000984 | 8 |
| P000454 | 7 |
| P000258 | 7 |
| P000510 | 7 |
| P001011 | 7 |
| P001235 | 7 |
| P001936 | 6 |
| P001647 | 6 |
| P000560 | 6 |

Products **P001113** and **P000984** recorded the highest number of purchase events with **8 purchases** each. The remaining top products recorded between **6 and 7 purchases**, indicating that completed purchases are relatively evenly distributed among popular products.

### Business Insight

Products with the highest purchase counts contribute directly to business revenue. These products can be highlighted as "Best Sellers" on the e-commerce platform and included in promotional campaigns, recommendation systems, and featured product sections to further increase sales.

### Visualization: Most Purchased Products

The following bar chart displays the top 10 most purchased products based on purchase events.

In [448]:
import plotly.express as px

top_purchase = (
    events[
        events["event_type"] == "purchase"
    ]["product_id"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_purchase.columns = ["Product ID", "Purchase Count"]

fig = px.bar(
    top_purchase,
    x="Product ID",
    y="Purchase Count",
    text="Purchase Count",
    title="Top 10 Most Purchased Products"
)

fig.update_layout(
    xaxis_title="Product ID",
    yaxis_title="Number of Purchases"
)

fig.show()

### Events Analysis Summary

### Key Findings

- The dataset contains **80,000 customer interaction events**.
- **View** events were the most common customer activity, followed by **Cart**, **Wishlist**, and **Purchase** events.
- Customer activity remained relatively stable throughout most of the year, with the highest engagement recorded in **July**.
- Several products consistently appeared among the most viewed, added-to-cart, wishlisted, and purchased products.
- The gap between product views and purchases indicates opportunities to improve customer conversion rates.

### Overall Business Insight

Customer event data provides valuable insights into user behavior during the shopping journey. By analyzing browsing patterns, cart activity, wishlist additions, and completed purchases, businesses can identify high-demand products, improve marketing strategies, optimize product recommendations, and increase conversion rates.

# Relational analysis 

### In the merged analysis, we are combining the tables to answer business questions that a single table cannot answer.
ex: Which brands receive the highest ratings? 
products has brand,
reviews has ratings 
products + reviews = brand with high ratings 


Merged Dataset Analysis :
 The merged analysis combines customer information, products, orders, order items, reviews, and user events to understand purchasing behavior, product performance, customer demographics, and revenue trends.

### Merge Orders with Users

Orders are merged with the Users dataset using the `user_id` column to associate each order with customer information.

In [449]:
orders_users = pd.merge(
    orders,
    users,
    on="user_id",
    how="left"
)

orders_users.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date
0,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22
1,O00000002,U003247,2025-04-15 01:18:27,completed,1666.85,Ryan Valencia,stevensonanthony@example.net,Male,South Mary,2024-03-23
2,O00000003,U007252,2025-04-27 15:37:48,processing,665.06,Tammy Fox,roberthenderson@example.org,Other,Wilsonton,2024-06-27
3,O00000004,U008986,2025-10-04 20:35:22,cancelled,689.50,Kurt Howard,nancy40@example.org,Female,New Barbarafurt,2024-12-04
4,O00000005,U008537,2024-11-13 08:15:18,cancelled,860.50,Kevin Krause,kyliechandler@example.net,Male,New Christophermouth,2025-03-12

### Merge Order Items

The order items dataset is merged with the previous dataset using `order_id` to include purchased products and quantities.

In [450]:
sales = pd.merge(
    orders_users,
    order_items,
    on=["order_id", "user_id"],
    how="left"
)

sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,order_item_id,product_id,quantity,item_price,item_total
0,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000001,P001758,2,8.07,16.14
1,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000002,P001119,1,74.08,74.08
2,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000003,P001794,1,576.97,576.97
3,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000004,P001038,1,22.47,22.47
4,O00000002,U003247,2025-04-15 01:18:27,completed,1666.85,Ryan Valencia,stevensonanthony@example.net,Male,South Mary,2024-03-23,I00000005,P000859,1,422.22,422.22

### Merge Products

The Products dataset is merged using `product_id` to include product information such as category, brand, price, and rating.

In [451]:
sales = pd.merge(
    sales,
    products,
    on="product_id",
    how="left"
)

sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,order_item_id,product_id,quantity,item_price,item_total,product_name,category,brand,price,rating
0,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000001,P001758,2,8.07,16.14,Everest Whole,Pet Supplies,Everest,8.07,2.69
1,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000002,P001119,1,74.08,74.08,Nimbus Minute,Beauty,Nimbus,74.08,3.62
2,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000003,P001794,1,576.97,576.97,Willow Treatment,Automotive,Willow,576.97,3.89
3,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,I00000004,P001038,1,22.47,22.47,Nimbus Deal,Books,Nimbus,22.47,4.85
4,O00000002,U003247,2025-04-15 01:18:27,completed,1666.85,Ryan Valencia,stevensonanthony@example.net,Male,South Mary,2024-03-23,I00000005,P000859,1,422.22,422.22,Pulse Decide,Electronics,Pulse,422.22,3.51

### Merge Reviews

The Reviews dataset is merged to associate customer ratings and reviews with purchased products.

In [452]:
sales = pd.merge(
    sales,
    reviews[
        [
            "order_id",
            "product_id",
            "rating",
            "review_text"
        ]
    ],
    on=["order_id", "product_id"],
    how="left"
)

sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,...,quantity,item_price,item_total,product_name,category,brand,price,rating_x,rating_y,review_text
0,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,2,8.07,16.14,Everest Whole,Pet Supplies,Everest,8.07,2.69,NaN,NaN
1,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,74.08,74.08,Nimbus Minute,Beauty,Nimbus,74.08,3.62,2.0,Color was different from images.
2,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,576.97,576.97,Willow Treatment,Automotive,Willow,576.97,3.89,NaN,NaN
3,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,22.47,22.47,Nimbus Deal,Books,Nimbus,22.47,4.85,NaN,NaN
4,O00000002,U003247,2025-04-15 01:18:27,completed,1666.85,Ryan Valencia,stevensonanthony@example.net,Male,South Mary,2024-03-23,...,1,422.22,422.22,Pulse Decide,Electronics,Pulse,422.22,3.51,NaN,NaN

### Final Dataset

The merged dataset contains customer information, order details, purchased products, and customer reviews in a single table for analysis.

In [453]:
sales.shape

(43537, 22)

### The merged dataset 
it combines customer information, order details, purchased products, product attributes, and customer reviews into one table. 43537 rows and 22 columns

In [454]:
sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,...,quantity,item_price,item_total,product_name,category,brand,price,rating_x,rating_y,review_text
0,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,2,8.07,16.14,Everest Whole,Pet Supplies,Everest,8.07,2.69,NaN,NaN
1,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,74.08,74.08,Nimbus Minute,Beauty,Nimbus,74.08,3.62,2.0,Color was different from images.
2,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,576.97,576.97,Willow Treatment,Automotive,Willow,576.97,3.89,NaN,NaN
3,O00000001,U009310,2025-09-09 14:52:37,processing,689.66,Christine Snyder,john14@example.com,Female,Jonestown,2024-02-22,...,1,22.47,22.47,Nimbus Deal,Books,Nimbus,22.47,4.85,NaN,NaN
4,O00000002,U003247,2025-04-15 01:18:27,completed,1666.85,Ryan Valencia,stevensonanthony@example.net,Male,South Mary,2024-03-23,...,1,422.22,422.22,Pulse Decide,Electronics,Pulse,422.22,3.51,NaN,NaN

### ratings :
products has a rating column (average product rating) rating_x

reviews has a rating column (customer's review rating) rating_y

In [455]:
sales = sales.rename(columns={
    "rating_x": "product_rating",
    "rating_y": "review_rating"
})

In [456]:
sales.columns

Index(['order_id', 'user_id', 'order_date', 'order_status', 'total_amount',
       'name', 'email', 'gender', 'city', 'signup_date', 'order_item_id',
       'product_id', 'quantity', 'item_price', 'item_total', 'product_name',
       'category', 'brand', 'price', 'product_rating', 'review_rating',
       'review_text'],
      dtype='str')

In [457]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 43537 entries, 0 to 43536
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        43537 non-null  str
 1   user_id         43537 non-null  str
 2   order_date      43537 non-null  datetime64[us]
 3   order_status    43537 non-null  str
 4   total_amount    43537 non-null  float64
 5   name            43537 non-null  str
 6   email           43537 non-null  str
 7   gender          43537 non-null  str
 8   city            43537 non-null  str
 9   signup_date     43537 non-null  datetime64[s]
 10  order_item_id   43537 non-null  str
 11  product_id      43537 non-null  str
 12  quantity        43537 non-null  int64
 13  item_price      43537 non-null  float64
 14  item_total      43537 non-null  float64
 15  product_name    43537 non-null  str
 16  category        43537 non-null  str
 17  brand           43537 non-null  str
 18  price           43537 non-null  float64
 19  product_rating  43537 non-null  float64
 20  review_rating   15023 non-null  float64
 21  review_text     15023 non-null  str
dtypes: datetime64[s](1), datetime64[us](1), float64(6), int64(1), str(13)
memory usage: 12.7 MB

In [458]:
sales.isnull().sum()

order_id              0
user_id               0
order_date            0
order_status          0
total_amount          0
name                  0
email                 0
gender                0
city                  0
signup_date           0
order_item_id         0
product_id            0
quantity              0
item_price            0
item_total            0
product_name          0
category              0
brand                 0
price                 0
product_rating        0
review_rating     28514
review_text       28514
dtype: int64

### Observation

The merged dataset contains **43,537 records** and **22 columns**.

Most columns contain complete data with no missing values. The `review_rating` and `review_text` columns contain missing values because not every purchased product has an associated customer review. This is expected and does not indicate a data quality issue.

# customer analysis 

### imp : 
Revenue-related questions → use item_total.

Sales volume (how many units sold) → use quantity.

Ratings and reviews → use review_rating.

### 1.Top 10 Customers by Total Spending :

This analysis identifies the customers who have spent the highest amount on the e-commerce platform. These customers are valuable because they contribute significantly to the company's revenue and may be suitable for loyalty programs and personalized marketing.

In [459]:
## using the merged dataset, use item_total.
top_customers = (
    sales.groupby(["user_id", "name"])["item_total"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_customers = top_customers.rename(
    columns={"item_total": "total_spending"}
)

top_customers

   user_id               name  total_spending
0  U009931        Meagan Case        13288.88
1  U006233     Willie Esparza        11234.22
2  U006469        Audrey Ware        10953.18
3  U008370  Brittany Carrillo        10190.11
4  U005702       Shawn Greene        10175.81
5  U009903    Jessica Russell        10118.31
6  U000006   Michael Santiago         9952.28
7  U004906     Brenda Winters         9538.69
8  U006231      Jerome Warner         9486.29
9  U007930    Robert Jennings         8947.98

In [460]:
import plotly.express as px

fig = px.bar(
    top_customers,
    x="name",
    y="total_spending",
    color="total_spending",
    text="total_spending",
    title="Top 10 Customers by Total Spending"
)

fig.update_layout(
    xaxis_title="Customer",
    yaxis_title="Total Spending ($)"
)

fig.show()

### business insight 
 The company should focus on retaining these high-value customers by offering loyalty rewards, personalized recommendations, and exclusive promotions. Improving customer retention among these customers can increase long-term revenue.

### 2.Revenue by City :
This analysis identifies the cities that generate the highest revenue for the business.

In [461]:
## using the merged dataset, use item_total.
revenue_city = (
    sales.groupby("city")["item_total"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

revenue_city = revenue_city.rename(
    columns={"item_total": "revenue"}
)

revenue_city

                 city   revenue
0       North Michael  22081.52
1          Port James  15893.39
2          East James  14930.35
3        South Robert  14047.15
4        Michaelmouth  13949.74
5           East Beth  13787.01
6    Lake Christopher  13526.77
7    Lake Alyssamouth  13288.88
8  North Williamville  12919.79
9      Johnsonchester  12886.54

In [462]:
fig = px.bar(
    revenue_city,
    x="city",
    y="revenue",
    color="revenue",
    text="revenue",
    title="Top 10 Cities by Revenue"
)

fig.update_layout(
    xaxis_title="City",
    yaxis_title="Revenue ($)"
)

fig.show()

### business Insight

The company can focus its marketing campaigns, inventory planning, and promotional activities in these high-performing cities to maximize sales while developing strategies to improve performance in lower-revenue regions.

### 3.Revenue by Gender

This analysis compares the total revenue generated by different gender groups to understand customer purchasing behavior.

In [463]:
revenue_gender = (
    sales.groupby("gender")["item_total"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

revenue_gender = revenue_gender.rename(
    columns={"item_total": "revenue"}
)

revenue_gender

   gender     revenue
0  Female  4076018.91
1   Other  4025433.21
2    Male  3818751.92

In [464]:
fig = px.pie(
    revenue_gender,
    names="gender",
    values="revenue",
    title="Revenue by Gender"
)

fig.show()

### Business Insight

Understanding customer spending by gender helps businesses create targeted marketing campaigns and personalized product recommendations.

# product analysis 

### 1.Best Selling Products

This analysis identifies the top 10 products based on the total number of units sold. It helps the business understand which products are the most popular among customers.

In [465]:
best_products = (
    sales.groupby(["product_id", "product_name"])["quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

best_products

  product_id        product_name  quantity
0    P001354  Harbor Development        54
1    P000519         Pulse Money        53
2    P000636      GreenLeaf Save        53
3    P000027      Willow Evening        53
4    P000515    Zenith Treatment        53
5    P000244        Everest Sell        53
6    P000762    Everest Response        52
7    P000825     Harbor National        52
8    P000443         Astra Great        52
9    P000507       Willow Beyond        51

In [466]:
fig = px.bar(
    best_products,
    x="product_name",
    y="quantity",
    color="quantity",
    text="quantity",
    title="Top 10 Best Selling Products"
)

fig.update_layout(
    xaxis_title="Product Name",
    yaxis_title="Units Sold"
)

fig.show()

### Business Insight

The company should ensure that these high-demand products remain well-stocked. They can also be promoted through advertising campaigns and bundled offers to further increase sales.

### 2.Revenue by Category

This analysis calculates the total revenue generated by each product category to identify the categories contributing the most to the business.

In [467]:
## need the merged sales table because the category information is stored with products.
revenue_category = (
    sales.groupby("category")["item_total"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

revenue_category = revenue_category.rename(
    columns={"item_total": "revenue"}
)

revenue_category

         category     revenue
0     Electronics  4961736.60
1      Automotive  2502343.59
2  Home & Kitchen  1132697.25
3          Sports   952403.23
4        Clothing   711315.86
5          Beauty   555775.00
6            Toys   385525.55
7    Pet Supplies   354035.82
8           Books   274837.11
9       Groceries    89534.03

In [468]:
fig = px.bar(
    revenue_category,
    x="category",
    y="revenue",
    color="revenue",
    text="revenue",
    title="Revenue by Category"
)

fig.update_layout(
    xaxis_title="Category",
    yaxis_title="Revenue ($)"
)

fig.show()

### Business Insight

High-revenue categories should receive greater focus in inventory planning, marketing campaigns, and promotional offers. Lower-performing categories can be evaluated for pricing or product assortment improvements.

### 3.Revenue by Brand

This analysis evaluates the revenue generated by each product brand to identify the strongest-performing brands.

In [469]:
revenue_brand = (
    sales.groupby("brand")["item_total"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

revenue_brand = revenue_brand.rename(
    columns={"item_total": "revenue"}
)

revenue_brand

        brand     revenue
0      Willow  1333667.54
1       Orion  1156616.67
2      Nimbus  1091999.73
3        Acme  1043228.86
4       Astra  1023587.77
5      Zenith  1013086.63
6   GreenLeaf   989095.30
7      Harbor   921626.85
8      Solace   891005.52
9       Pulse   882109.91
10    Everest   832888.12
11    NeoTech   741291.14

In [470]:
fig = px.bar(
    revenue_brand,
    x="brand",
    y="revenue",
    color="revenue",
    text="revenue",
    title="Revenue by Brand"
)

fig.update_layout(
    xaxis_title="Brand",
    yaxis_title="Revenue ($)"
)

fig.show()

### Business Insight

High-performing brands should be prioritized for inventory management, promotional campaigns, and strategic partnerships. Understanding brand performance also helps the business optimize its product portfolio.

# Review analysis 

### 1.Average Rating by Category

This analysis calculates the average customer review rating for each product category. It helps identify which categories receive the highest customer satisfaction.

This section focuses on customer feedback and satisfaction using the review_rating column.

In [471]:
avg_rating_category = (
    sales.groupby("category")["review_rating"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

avg_rating_category

         category  review_rating
0    Pet Supplies       3.584894
1          Beauty       3.565028
2            Toys       3.554485
3     Electronics       3.544715
4           Books       3.544236
5        Clothing       3.539417
6  Home & Kitchen       3.529614
7       Groceries       3.526119
8      Automotive       3.524320
9          Sports       3.520231

In [472]:
fig = px.bar(
    avg_rating_category,
    x="category",
    y="review_rating",
    color="review_rating",
    text=avg_rating_category["review_rating"].round(2),
    title="Average Review Rating by Category"
)

fig.update_layout(
    xaxis_title="Category",
    yaxis_title="Average Rating"
)

fig.show()

### Business Insight

Categories with consistently high customer ratings should be promoted more aggressively, while lower-rated categories should be reviewed for product quality, pricing, or customer expectations.

### 8.2 Average Rating by Brand

This analysis evaluates the average customer review rating for each brand to identify the highest-rated brands.

In [473]:
avg_rating_brand = (
    sales.groupby("brand")["review_rating"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

avg_rating_brand

        brand  review_rating
0       Orion       3.604669
1        Acme       3.561511
2   GreenLeaf       3.556236
3     NeoTech       3.551969
4      Harbor       3.542169
5      Willow       3.538401
6      Zenith       3.537568
7       Pulse       3.536893
8      Solace       3.530303
9     Everest       3.527755
10      Astra       3.525452
11     Nimbus       3.518231

In [474]:
fig = px.bar(
    avg_rating_brand,
    x="brand",
    y="review_rating",
    color="review_rating",
    text=avg_rating_brand["review_rating"].round(2),
    title="Average Review Rating by Brand"
)

fig.update_layout(
    xaxis_title="Brand",
    yaxis_title="Average Rating"
)

fig.show()

### Business Insight

Highly rated brands can be featured more prominently in promotions, while brands with lower ratings may require quality improvements or better customer support.

### 3.Most Reviewed Products

This analysis identifies the products that have received the highest number of customer reviews.

In [475]:
most_reviewed = (
    sales.groupby(["product_id", "product_name"])["review_rating"]
    .count()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

most_reviewed = most_reviewed.rename(
    columns={"review_rating": "number_of_reviews"}
)

most_reviewed

  product_id      product_name  number_of_reviews
0    P000497        Acme Owner                 20
1    P001387    Harbor Success                 18
2    P001055     Harbor Wonder                 18
3    P000902    GreenLeaf Card                 17
4    P000762  Everest Response                 17
5    P000178       Solace Easy                 16
6    P000233      Zenith Might                 16
7    P000152       Zenith Soon                 16
8    P001036    Pulse Security                 16
9    P001925   Willow Hospital                 16

In [476]:
fig = px.bar(
    most_reviewed,
    x="product_name",
    y="number_of_reviews",
    color="number_of_reviews",
    text="number_of_reviews",
    title="Top 10 Most Reviewed Products"
)

fig.update_layout(
    xaxis_title="Product Name",
    yaxis_title="Number of Reviews"
)

fig.show()

### Business Insight

Products with a large number of customer reviews provide valuable social proof and can improve customer confidence. Highlighting these products may increase future sales and customer trust.

# Sales analysis 

### 1.Monthly Revenue

This analysis examines the monthly revenue generated by the business. It helps identify seasonal sales trends and monthly business performance.

use the orders table because it contains one row per order. This avoids counting the same order multiple times after the merge.

In [477]:
monthly_revenue = (
    orders.groupby(orders["order_date"].dt.month)["total_amount"]
    .sum()
    .reset_index()
)

monthly_revenue.columns = ["Month", "Revenue"]

monthly_revenue

    Month     Revenue
0       1  1046038.87
1       2   974090.97
2       3  1046877.95
3       4  1077469.41
4       5  1091377.77
5       6  1056448.28
6       7  1137336.74
7       8  1031340.01
8       9  1051443.49
9      10  1050549.94
10     11   789393.85
11     12   566301.67

In [478]:
fig = px.line(
    monthly_revenue,
    x="Month",
    y="Revenue",
    markers=True,
    title="Monthly Revenue"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue ($)"
)

fig.show()

### business Insight

Understanding monthly revenue trends helps the business plan inventory, marketing campaigns, and promotional activities during peak and low sales periods.

### Monthly Revenue by Category
This analysis compares monthly revenue across different product categories to understand how category performance changes over time.

In [479]:
monthly_category = (
    sales.groupby(
        [sales["order_date"].dt.month, "category"]
    )["item_total"]
    .sum()
    .reset_index()
)

monthly_category.columns = ["Month", "Category", "Revenue"]

monthly_category.head()

   Month     Category    Revenue
0      1   Automotive  225611.70
1      1       Beauty   51086.79
2      1        Books   23543.40
3      1     Clothing   70677.91
4      1  Electronics  408119.87

In [480]:
fig = px.line(
    monthly_category,
    x="Month",
    y="Revenue",
    color="Category",
    markers=True,
    title="Monthly Revenue by Category"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue ($)"
)

fig.show()

### Business Insight

Tracking category performance over time helps the business identify seasonal demand and make better decisions about inventory, pricing, and promotional campaigns.

### Average Order Value
Average Order Value (AOV) measures the average amount spent by customers in each order. It is an important metric for evaluating customer purchasing behavior.

In [481]:
average_order_value = orders["total_amount"].mean()

print(f"Average Order Value: ${average_order_value:.2f}")

Average Order Value: $595.93

In [482]:
aov = pd.DataFrame({
    "Metric": ["Average Order Value"],
    "Value": [average_order_value]
})

fig = px.bar(
    aov,
    x="Metric",
    y="Value",
    text="Value",
    title="Average Order Value"
)

fig.update_layout(
    yaxis_title="Value ($)"
)

fig.show()

### Business Insight

Increasing the Average Order Value can improve revenue without increasing the number of customers. Businesses can achieve this through product bundles, cross-selling, upselling, and promotional offers.

# Customer Behavior Analysis
### 1.Most Viewed Products
This analysis identifies the products that customers viewed the most. High view counts indicate products that attract customer attention and interest.

use the events dataset because it records customer interactions such as view, cart, wishlist, and purchase.

In [483]:
most_viewed = (
    events[events["event_type"] == "view"]
    .groupby("product_id")
    .size()
    .sort_values(ascending=False)
    .head(10)
    .reset_index(name="views")
)

most_viewed = most_viewed.merge(
    products[["product_id", "product_name"]],
    on="product_id",
    how="left"
)

most_viewed

  product_id  views     product_name
0    P000516     46    Nimbus Threat
1    P001435     42       Harbor Eye
2    P000608     42  GreenLeaf Visit
3    P001771     42  GreenLeaf Guess
4    P001942     42   Everest School
5    P000101     42  Willow Cultural
6    P001832     42    Orion Medical
7    P001193     42      Zenith Team
8    P001384     41        Pulse Few
9    P000050     41     Everest Easy

In [484]:
fig = px.bar(
    most_viewed,
    x="product_name",
    y="views",
    color="views",
    text="views",
    title="Top 10 Most Viewed Products"
)

fig.update_layout(
    xaxis_title="Product Name",
    yaxis_title="Number of Views"
)

fig.show()

### Business Insight

Products with high view counts are popular among customers and can be highlighted in promotional campaigns. If these products have low sales, pricing, reviews, or product descriptions should be evaluated.

### 2.Most Added-to-Cart Products

This analysis identifies the products that customers add to their shopping carts most frequently.

In [485]:
most_cart = (
    events[events["event_type"] == "cart"]
    .groupby("product_id")
    .size()
    .sort_values(ascending=False)
    .head(10)
    .reset_index(name="cart_count")
)

most_cart = most_cart.merge(
    products[["product_id", "product_name"]],
    on="product_id",
    how="left"
)

most_cart

  product_id  cart_count      product_name
0    P001938          17    Harbor Himself
1    P001112          16       Willow Sing
2    P001086          16  GreenLeaf Course
3    P000233          16      Zenith Might
4    P000967          16        Astra Tend
5    P000604          16     Pulse Economy
6    P001689          15  Willow Condition
7    P001651          15        Acme Those
8    P000268          15    Willow Officer
9    P001815          15    Harbor Despite

In [486]:
fig = px.bar(
    most_cart,
    x="product_name",
    y="cart_count",
    color="cart_count",
    text="cart_count",
    title="Top 10 Most Added-to-Cart Products"
)

fig.update_layout(
    xaxis_title="Product Name",
    yaxis_title="Cart Count"
)

fig.show()

### Business Insight

Products with high cart activity are likely to convert into sales. Businesses should ensure these products remain in stock and consider offering discounts or bundle deals to encourage purchases.

### 3 Products with High Views but Low Purchases


This analysis compares product views with purchase events to identify products that attract customer interest but have relatively low purchase activity.

In [487]:
views = (
    events[events["event_type"] == "view"]
    .groupby("product_id")
    .size()
    .reset_index(name="views")
)

purchases = (
    events[events["event_type"] == "purchase"]
    .groupby("product_id")
    .size()
    .reset_index(name="purchases")
)

conversion = views.merge(
    purchases,
    on="product_id",
    how="left"
)

conversion["purchases"] = conversion["purchases"].fillna(0)

conversion["conversion_rate"] = (
    conversion["purchases"] / conversion["views"] * 100
).round(2)

conversion = conversion.merge(
    products[["product_id", "product_name"]],
    on="product_id",
    how="left"
)

high_views_low_purchase = (
    conversion.sort_values(
        by=["views", "conversion_rate"],
        ascending=[False, True]
    )
    .head(10)
)

high_views_low_purchase

     product_id  views  purchases  conversion_rate     product_name
515     P000516     46        1.0             2.17    Nimbus Threat
1434    P001435     42        1.0             2.38       Harbor Eye
1831    P001832     42        1.0             2.38    Orion Medical
100     P000101     42        2.0             4.76  Willow Cultural
1941    P001942     42        2.0             4.76   Everest School
607     P000608     42        3.0             7.14  GreenLeaf Visit
1192    P001193     42        3.0             7.14      Zenith Team
1770    P001771     42        4.0             9.52  GreenLeaf Guess
590     P000591     41        0.0             0.00   GreenLeaf Pull
1102    P001103     41        0.0             0.00    GreenLeaf Old

In [488]:
fig = px.scatter(
    high_views_low_purchase,
    x="views",
    y="conversion_rate",
    size="views",
    hover_name="product_name",
    title="Products with High Views but Low Purchases"
)

fig.update_layout(
    xaxis_title="Views",
    yaxis_title="Conversion Rate (%)"
)

fig.show()

### Business Insight

Products with high views but low purchases should be reviewed for pricing, product descriptions, customer reviews, or checkout experience. Improving these factors may increase conversion rates and overall sales.

# Key Findings

Based on the exploratory data analysis, the following key insights were identified:

- The dataset contains information about users, products, orders, reviews, and customer events.
- Monthly revenue varies throughout the year, indicating seasonal sales trends.
- A small group of customers contributes significantly to total revenue.
- Revenue differs across product categories and brands.
- Some products receive higher customer ratings than others, indicating differences in customer satisfaction.
- Customer behavior analysis shows that some products receive many views but relatively fewer purchases, suggesting opportunities to improve conversion rates.
- Product categories and brands with higher revenue should receive greater focus in marketing and inventory planning.
- Customer reviews provide valuable insights into product quality and customer experience.



This project analyzed an e-commerce dataset using Python, Pandas, Plotly, and MySQL. The data was cleaned, explored, and combined to generate meaningful business insights.

The analysis identified customer purchasing patterns, product performance, sales trends, customer reviews, and browsing behavior. These insights can help businesses improve inventory management, marketing strategies, customer engagement, and overall business performance.

The findings from this analysis can be presented through an interactive Streamlit dashboard, allowing users to explore key business metrics and visualizations in an easy-to-use interface.

In [489]:
sales.to_csv("sales.csv", index=False)

In [490]:
import os

os.listdir()

['.DS_Store',
 'Ecommerce_Dashboard',
 'fashion_sales.csv',
 'Ecommerce_EDA1.ipynb',
 'sales.csv',
 'Ecommerce_EDA2.ipynb']

# Fashion dataset 

Customers often spend significant time searching through numerous fashion products without receiving personalized recommendations. This project aims to develop a Personalized Fashion Shopping Assistant that analyzes customer preferences, product information, and purchasing behavior to recommend suitable fashion products and enhance the shopping experience.



Initially i explored the complete e-commerce dataset to understand its structure, data quality, customer behavior, and product distribution. After identifying the relevant category for my project, I created a fashion-specific dataset using the Clothing category.

In [491]:
sales["category"].value_counts()

category
Pet Supplies      4729
Toys              4719
Clothing          4605
Beauty            4547
Books             4312
Electronics       4238
Automotive        4237
Home & Kitchen    4226
Sports            4054
Groceries         3870
Name: count, dtype: int64

In [492]:
sales[
    sales["category"] == "Clothing"
][["product_name","brand"]].head(30)

       product_name      brand
13      Nimbus When     Nimbus
18     Harbor Night     Harbor
24    Astra Without      Astra
27       Orion Most      Orion
31       Nimbus Sit     Nimbus
43      Harbor Beat     Harbor
48       Solace Car     Solace
61       Astra Test      Astra
75     Harbor Night     Harbor
85       Acme Wrong       Acme
90      Willow Site     Willow
118    Everest Drug    Everest
140      Orion Side      Orion
159  Everest Single    Everest
164   Willow Remain     Willow
165      Astra Tend      Astra
182  GreenLeaf Wall  GreenLeaf
190  NeoTech Nearly    NeoTech
209   GreenLeaf Act  GreenLeaf
211  NeoTech Decide    NeoTech
243    Everest Real    Everest
247      Solace And     Solace
263      Acme Wrong       Acme
268     Nimbus When     Nimbus
277   Astra Benefit      Astra
285     Orion Short      Orion
290       Acme Mind       Acme
293    Everest Rock    Everest
301    Harbor Until     Harbor
307     Willow Site     Willow

In [493]:
sales[
    sales["product_name"].str.contains(
        "bag|belt|cap|hat|watch|wallet|backpack|scarf|sunglasses",
        case=False,
        na=False
    )
][["product_name","category"]].head(30)

            product_name        category
60            Nimbus Bag          Beauty
291           Nimbus Bag          Beauty
581        Orion Capital     Electronics
1015         Zenith What          Beauty
1416       NeoTech Watch           Books
1613       Astra Capital  Home & Kitchen
1625  GreenLeaf Whatever            Toys
1667           Orion Bag          Beauty
1883           Orion Bag          Beauty
1910      Orion Whatever     Electronics
2190      Orion Whatever           Books
2286        Nimbus Watch            Toys
2340  GreenLeaf Whatever            Toys
2613          Nimbus Bag          Beauty
3088           Orion Bag          Beauty
3127          Nimbus Bag          Beauty
3772         Zenith What          Beauty
3805       NeoTech Watch           Books
3807         Zenith What          Beauty
4091       Orion Capital     Electronics
4172  GreenLeaf Whatever            Toys
4377         Zenith What          Beauty
4542       NeoTech Watch           Books
4843       Astra Capital  Home & Kitchen
4897  GreenLeaf Whatever            Toys
4936        NeoTech What    Pet Supplies
5289          Nimbus Bag          Beauty
5420      Orion Whatever     Electronics
5494      Orion Whatever     Electronics
5721      Orion Whatever           Books

In [494]:
fashion_sales = sales[sales["category"] == "Clothing"].copy()

In [495]:
fashion_sales["category"].value_counts()

category
Clothing    4605
Name: count, dtype: int64

In [496]:
fashion_sales.to_csv("fashion_sales.csv", index=False)

In [497]:
fashion_sales

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,...,quantity,item_price,item_total,product_name,category,brand,price,product_rating,review_rating,review_text
13,O00000004,U008986,2025-10-04 20:35:22,cancelled,689.50,Kurt Howard,nancy40@example.org,Female,New Barbarafurt,2024-12-04,...,2,67.54,135.08,Nimbus When,Clothing,Nimbus,67.54,3.58,NaN,NaN
18,O00000006,U003449,2024-10-13 09:02:27,completed,2258.34,Mason Owens,wharris@example.org,Other,Danielfort,2025-05-17,...,3,209.10,627.30,Harbor Night,Clothing,Harbor,209.10,3.68,NaN,NaN
24,O00000009,U000610,2025-10-29 07:00:11,cancelled,229.02,Rachel Taylor,parkerrichard@example.org,Male,Howardmouth,2025-05-15,...,2,114.51,229.02,Astra Without,Clothing,Astra,114.51,2.87,NaN,NaN
27,O00000011,U004470,2025-08-14 09:59:55,shipped,1016.61,Morgan Lopez,michael10@example.com,Other,South Peggy,2025-10-14,...,1,151.39,151.39,Orion Most,Clothing,Orion,151.39,3.99,NaN,NaN
31,O00000012,U009480,2025-08-27 09:57:49,cancelled,600.23,Gabrielle Serrano,rachelblackwell@example.net,Other,New Timothy,2025-01-31,...,2,37.65,75.30,Nimbus Sit,Clothing,Nimbus,37.65,4.54,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43503,O00019990,U009792,2025-08-05 12:43:27,returned,1624.01,David Thomas,kowens@example.com,Male,Lake Matthewview,2024-05-11,...,2,253.60,507.20,Everest Single,Clothing,Everest,253.60,3.94,NaN,NaN
43511,O00019991,U002900,2024-09-12 10:14:57,shipped,301.84,Yvonne Thompson,jrobinson@example.com,Female,Taylorside,2025-09-19,...,1,80.66,80.66,Acme Answer,Clothing,Acme,80.66,4.68,NaN,NaN
43512,O00019992,U001855,2025-03-05 01:19:04,cancelled,2164.38,Robert Figueroa,iharrington@example.org,Other,New Laceymouth,2025-05-03,...,1,97.47,97.47,Solace Create,Clothing,Solace,97.47,2.92,NaN,NaN
43515,O00019992,U001855,2025-03-05 01:19:04,cancelled,2164.38,Robert Figueroa,iharrington@example.org,Other,New Laceymouth,2025-05-03,...,2,262.79,525.58,Acme Soldier,Clothing,Acme,262.79,4.30,NaN,NaN
43520,O00019994,U006442,2025-01-16 08:39:11,shipped,790.35,Anna Hernandez,donaldnguyen@example.com,Female,Beasleyville,2025-02-20,...,1,28.05,28.05,NeoTech Opportunity,Clothing,NeoTech,28.05,4.84,3.0,Decent product for the price.


# Fashion Exploratory Data Analysis (EDA)

The purpose of this section is to explore the fashion dataset and understand customer behavior, product performance, sales trends, and customer preferences related to fashion products.

### dataset overview :

This analysis shows the total number of unique fashion products available in the dataset.

In [498]:
fashion_sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,...,quantity,item_price,item_total,product_name,category,brand,price,product_rating,review_rating,review_text
13,O00000004,U008986,2025-10-04 20:35:22,cancelled,689.50,Kurt Howard,nancy40@example.org,Female,New Barbarafurt,2024-12-04,...,2,67.54,135.08,Nimbus When,Clothing,Nimbus,67.54,3.58,NaN,NaN
18,O00000006,U003449,2024-10-13 09:02:27,completed,2258.34,Mason Owens,wharris@example.org,Other,Danielfort,2025-05-17,...,3,209.10,627.30,Harbor Night,Clothing,Harbor,209.10,3.68,NaN,NaN
24,O00000009,U000610,2025-10-29 07:00:11,cancelled,229.02,Rachel Taylor,parkerrichard@example.org,Male,Howardmouth,2025-05-15,...,2,114.51,229.02,Astra Without,Clothing,Astra,114.51,2.87,NaN,NaN
27,O00000011,U004470,2025-08-14 09:59:55,shipped,1016.61,Morgan Lopez,michael10@example.com,Other,South Peggy,2025-10-14,...,1,151.39,151.39,Orion Most,Clothing,Orion,151.39,3.99,NaN,NaN
31,O00000012,U009480,2025-08-27 09:57:49,cancelled,600.23,Gabrielle Serrano,rachelblackwell@example.net,Other,New Timothy,2025-01-31,...,2,37.65,75.30,Nimbus Sit,Clothing,Nimbus,37.65,4.54,NaN,NaN

In [499]:
fashion_sales.shape

(4605, 22)

In [500]:
fashion_sales.info()

<class 'pandas.DataFrame'>
Index: 4605 entries, 13 to 43520
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        4605 non-null   str
 1   user_id         4605 non-null   str
 2   order_date      4605 non-null   datetime64[us]
 3   order_status    4605 non-null   str
 4   total_amount    4605 non-null   float64
 5   name            4605 non-null   str
 6   email           4605 non-null   str
 7   gender          4605 non-null   str
 8   city            4605 non-null   str
 9   signup_date     4605 non-null   datetime64[s]
 10  order_item_id   4605 non-null   str
 11  product_id      4605 non-null   str
 12  quantity        4605 non-null   int64
 13  item_price      4605 non-null   float64
 14  item_total      4605 non-null   float64
 15  product_name    4605 non-null   str
 16  category        4605 non-null   str
 17  brand           4605 non-null   str
 18  price           4605 non-null   float64
 19  product_rating  4605 non-null   float64
 20  review_rating   1611 non-null   float64
 21  review_text     1611 non-null   str
dtypes: datetime64[s](1), datetime64[us](1), float64(6), int64(1), str(13)
memory usage: 1.4 MB

In [501]:
fashion_sales["category"].unique()

<ArrowStringArray>
['Clothing']
Length: 1, dtype: str

In [502]:
# missing values :
fashion_sales.isnull().sum()

order_id             0
user_id              0
order_date           0
order_status         0
total_amount         0
name                 0
email                0
gender               0
city                 0
signup_date          0
order_item_id        0
product_id           0
quantity             0
item_price           0
item_total           0
product_name         0
category             0
brand                0
price                0
product_rating       0
review_rating     2994
review_text       2994
dtype: int64

#### The missing values in review_rating and review_text are expected because not every customer submits a product review.

In [503]:
# duplicate values :
fashion_sales.duplicated().sum()

np.int64(0)

In [504]:
# data types : 
fashion_sales.dtypes

order_id                     str
user_id                      str
order_date        datetime64[us]
order_status                 str
total_amount             float64
name                         str
email                        str
gender                       str
city                         str
signup_date        datetime64[s]
order_item_id                str
product_id                   str
quantity                   int64
item_price               float64
item_total               float64
product_name                 str
category                     str
brand                        str
price                    float64
product_rating           float64
review_rating            float64
review_text                  str
dtype: object

### 1.Total Unique Fashion Products :

This analysis calculates the total number of unique fashion products available in the dataset.

In [505]:
fashion_sales["product_id"].nunique()

213

### 2.total unique fashion customers :

In [506]:

fashion_sales["user_id"].nunique()

3377

### 3.Total Fashion Revenue
This analysis calculates the total revenue generated from fashion product sales.

In [507]:
fashion_sales["item_total"].sum()

np.float64(711315.86)

### 4.Average Fashion Order Value
This analysis calculates the average value of fashion orders.(1 item)

In [508]:
fashion_sales.groupby("order_id")["item_total"].sum().mean()

np.float64(171.31884874759152)

### 5.Top 10 Fashion Brands by Revenue
This analysis identifies the fashion brands generating the highest revenue.

In [509]:
top_brand_revenue = (
    fashion_sales.groupby("brand", as_index=False)["item_total"]
    .sum()
    .sort_values(by="item_total", ascending=False)
    .head(10)
)

top_brand_revenue

        brand  item_total
2     Everest    91625.32
7       Orion    85972.08
3   GreenLeaf    85355.95
4      Harbor    78759.05
11     Zenith    65048.18
5     NeoTech    57626.83
9      Solace    57199.98
0        Acme    52696.45
1       Astra    51692.92
10     Willow    43345.78

In [510]:
import plotly.express as px

fig = px.bar(
    top_brand_revenue,
    x="brand",
    y="item_total",
    color="item_total",
    text="item_total",
    title="Top 10 Fashion Brands by Revenue",
    labels={
        "brand": "Brand",
        "item_total": "Revenue ($)"
    }
)

fig.update_traces(
    texttemplate="$%{text:,.2f}",
    textposition="outside"
)

fig.update_layout(
    xaxis_title="Brand",
    yaxis_title="Revenue ($)"
)

fig.show()

### 6.Best Selling Fashion Products
 This analysis identifies the best-selling fashion products based on quantity sold.

In [511]:
best_products = (
    fashion_sales.groupby("product_name")["quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

best_products

product_name
Solace Everyone     68
Zenith Within       58
Solace School       55
Harbor National     52
Everest Response    52
Solace Create       46
GreenLeaf Rule      45
Acme Then           45
Orion Enter         44
Acme Wrong          43
Name: quantity, dtype: int64

### 7.top Rated Fashion Products
This analysis identifies the fashion products with the highest average customer ratings.

In [512]:
top_rated = (
    fashion_sales.groupby("product_name")["review_rating"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

top_rated

product_name
Orion Make            4.750000
Astra Clearly         4.666667
Harbor Medical        4.500000
Harbor Race           4.500000
NeoTech Production    4.400000
Pulse Wait            4.400000
Orion Role            4.400000
Everest Benefit       4.333333
Nimbus Wish           4.333333
Nimbus Possible       4.333333
Name: review_rating, dtype: float64

### 8.Fashion Revenue by Brand
 This analysis compares the revenue generated by different fashion brands.

In [513]:
brand_revenue = (
    fashion_sales.groupby("brand")["item_total"]
    .sum()
    .sort_values(ascending=False)
     
)

brand_revenue

brand
Everest      91625.32
Orion        85972.08
GreenLeaf    85355.95
Harbor       78759.05
Zenith       65048.18
NeoTech      57626.83
Solace       57199.98
Acme         52696.45
Astra        51692.92
Willow       43345.78
Pulse        26048.23
Nimbus       15945.09
Name: item_total, dtype: float64

### 9.Fashion Revenue by Gender
This analysis shows the revenue contribution of customers based on gender.

In [514]:
gender_revenue = (
    fashion_sales.groupby("gender")["item_total"]
    .sum()
    .reset_index()
)

gender_revenue

   gender  item_total
0  Female   241495.66
1    Male   229170.62
2   Other   240649.58

In [515]:
import plotly.express as px

fig = px.pie(
    gender_revenue,
    names="gender",
    values="item_total",
    title="Fashion Revenue by Gender",
    hole=0.4
)

fig.show()

### 10.Fashion Revenue by City

This analysis identifies the cities generating the highest fashion sales revenue.

In [516]:
fashion_sales.groupby("city")["item_total"] \
.sum() \
.sort_values(ascending=False) \
.head(10)

city
Ericksonstad     1878.30
New David        1839.63
New Daniel       1825.34
Nicolemouth      1746.97
New Melissa      1586.45
Brownmouth       1555.56
Moralesbury      1487.48
Jamesport        1385.96
Smithbury        1335.21
West Michelle    1318.91
Name: item_total, dtype: float64

### 11.Monthly Fashion Revenue

This analysis shows how fashion revenue changes across different months.

In [517]:
fashion_sales.groupby(
    fashion_sales["order_date"].dt.month
)["item_total"].sum()

order_date
1     70677.91
2     55303.16
3     68386.38
4     60862.10
5     63365.77
6     65133.52
7     57543.42
8     61943.28
9     63305.08
10    64184.76
11    48030.23
12    32580.25
Name: item_total, dtype: float64

### 12.Monthly Fashion Orders

This analysis shows the number of fashion orders placed each month.

In [518]:
fashion_sales.groupby(
    fashion_sales["order_date"].dt.month
)["order_id"].nunique()

order_date
1     385
2     336
3     382
4     360
5     377
6     353
7     367
8     375
9     378
10    392
11    261
12    186
Name: order_id, dtype: int64

### 13.Fashion Rating Distribution

This analysis shows how customers rated fashion products.

In [519]:
fashion_sales["review_rating"].value_counts().sort_index()

review_rating
1.0     63
2.0    236
3.0    451
4.0    491
5.0    370
Name: count, dtype: int64

In [520]:
import plotly.express as px

review_rating = (
    fashion_sales["review_rating"]
    .value_counts()
    .sort_index()
    .reset_index()
)

review_rating.columns = ["Review Rating", "Count"]

fig = px.bar(
    review_rating,
    x="Review Rating",
    y="Count",
    color="Count",
    text="Count",
    title="Fashion Review Rating Distribution"
)

fig.update_traces(textposition="outside")

fig.show()

### 14.Most Purchased Fashion Brands

This analysis identifies the brands with the highest quantity of products sold.

In [521]:
fashion_sales.groupby("brand")["quantity"] \
.sum() \
.sort_values(ascending=False)

brand
Harbor       821
GreenLeaf    757
Everest      680
Orion        675
Zenith       524
NeoTech      519
Acme         500
Solace       480
Willow       439
Astra        433
Pulse        348
Nimbus       236
Name: quantity, dtype: int64

In [522]:
fashion_sales.shape

(4605, 22)

# Fashion Business Analytics

Fashion Business Analytics focuses on analyzing sales performance, customer purchasing behavior, product performance, and brand performance within the fashion category. These analyses provide meaningful business insights that help identify top-performing products, valuable customers, high-revenue brands, and sales trends. The findings from this section will also support the development of a Personalized Fashion Shopping Assistant by understanding customer preferences and purchasing patterns.

# 1.Top 10 Fashion Customers by Spending

In [523]:
top_customers = (
    fashion_sales.groupby("user_id", as_index=False)["item_total"]
    .sum()
    .sort_values(by="item_total", ascending=False)
    .head(10)
)

top_customers

      user_id  item_total
939   U002754     1878.30
94    U000262     1586.45
1328  U003827     1487.48
3169  U009414     1167.86
635   U001880     1072.86
2971  U008771     1065.59
871   U002553     1033.51
65    U000180     1028.55
1028  U002995      998.10
1212  U003506      990.25

In [524]:
import plotly.express as px

fig = px.bar(
    top_customers,
    x="user_id",
    y="item_total",
    color="item_total",
    text="item_total",
    title="Top 10 Fashion Customers by Spending",
    labels={
        "user_id": "Customer ID",
        "item_total": "Total Spending ($)"
    }
)

fig.update_traces(textposition="outside")

fig.show()

### 2. Fashion Revenue by Gender

In [525]:
gender_revenue = (
    fashion_sales.groupby("gender", as_index=False)["item_total"]
    .sum()
)

gender_revenue

   gender  item_total
0  Female   241495.66
1    Male   229170.62
2   Other   240649.58

In [526]:
fig = px.pie(
    gender_revenue,
    names="gender",
    values="item_total",
    title="Fashion Revenue by Gender",
    hole=0.4
)

fig.update_traces(textinfo="percent+label")

fig.show()

### 3.Top 10 Fashion Brands by Revenue.

In [527]:
top_brand_revenue = (
    fashion_sales.groupby("brand", as_index=False)["item_total"]
    .sum()
    .sort_values(by="item_total", ascending=False)
    .head(10)
)

top_brand_revenue

        brand  item_total
2     Everest    91625.32
7       Orion    85972.08
3   GreenLeaf    85355.95
4      Harbor    78759.05
11     Zenith    65048.18
5     NeoTech    57626.83
9      Solace    57199.98
0        Acme    52696.45
1       Astra    51692.92
10     Willow    43345.78

In [528]:
fig = px.bar(
    top_brand_revenue,
    x="brand",
    y="item_total",
    color="item_total",
    text="item_total",
    title="Top 10 Fashion Brands by Revenue",
    labels={
        "brand": "Brand",
        "item_total": "Revenue ($)"
    }
)

fig.update_traces(textposition="outside")

fig.show()

### 4. Best Selling Fashion Products

In [529]:
best_products = (
    fashion_sales.groupby("product_name", as_index=False)["quantity"]
    .sum()
    .sort_values(by="quantity", ascending=False)
    .head(10)
)

best_products

         product_name  quantity
169   Solace Everyone        68
209     Zenith Within        58
174     Solace School        55
92    Harbor National        52
47   Everest Response        52
167     Solace Create        46
73     GreenLeaf Rule        45
12          Acme Then        45
131       Orion Enter        44
14         Acme Wrong        43

In [530]:
import plotly.express as px

fig = px.bar(
    best_products,
    x="product_name",
    y="quantity",
    color="quantity",
    text="quantity",
    title="Top 10 Best Selling Fashion Products",
    labels={
        "product_name": "Product",
        "quantity": "Quantity Sold"
    }
)

fig.update_traces(textposition="outside")

fig.show()

### 5. Fashion Revenue by City - top 10

In [531]:
city_revenue = (
    fashion_sales.groupby("city", as_index=False)["item_total"]
    .sum()
    .sort_values(by="item_total", ascending=False)
    .head(10)
)

city_revenue

               city  item_total
618    Ericksonstad     1878.30
1513      New David     1839.63
1509     New Daniel     1825.34
1676    Nicolemouth     1746.97
1595    New Melissa     1586.45
171      Brownmouth     1555.56
1421    Moralesbury     1487.48
819       Jamesport     1385.96
2355      Smithbury     1335.21
2919  West Michelle     1318.91

In [532]:
fig = px.bar(
    city_revenue,
    x="city",
    y="item_total",
    color="item_total",
    text="item_total",
    title="Top 10 Cities by Fashion Revenue",
    labels={
        "city": "City",
        "item_total": "Revenue ($)"
    }
)

fig.update_traces(textposition="outside")

fig.show()

### 6. Monthly Fashion Revenue

In [533]:
fashion_sales["order_month"] = fashion_sales["order_date"].dt.to_period("M")

In [534]:
monthly_revenue = (
    fashion_sales.groupby("order_month", as_index=False)["item_total"]
    .sum()
)

monthly_revenue["order_month"] = monthly_revenue["order_month"].astype(str)

In [535]:
fig = px.line(
    monthly_revenue,
    x="order_month",
    y="item_total",
    markers=True,
    title="Monthly Fashion Revenue"
)

fig.update_xaxes(
    tickmode="array",
    tickvals=[
        "2024-01","2024-07","2024-12",
        "2025-01","2025-07"
    ],
    ticktext=[
        "Jan-2024","Jul-2024","Dec-2024",
        "Jan-2025","Jul-2025"
    ],
    tickangle=45
)

fig.show()

### 7. Monthly Fashion Orders

In [536]:
monthly_orders = (
    fashion_sales.groupby("order_month")["order_id"]
    .nunique()
    .reset_index(name="Number of Orders")
)

monthly_orders["order_month"] = monthly_orders["order_month"].astype(str)

monthly_orders

   order_month  Number of Orders
0      2024-01               182
1      2024-02               173
2      2024-03               196
3      2024-04               184
4      2024-05               177
5      2024-06               186
6      2024-07               191
7      2024-08               191
8      2024-09               185
9      2024-10               184
10     2024-11               180
11     2024-12               186
12     2025-01               203
13     2025-02               163
14     2025-03               186
15     2025-04               176
16     2025-05               200
17     2025-06               167
18     2025-07               176
19     2025-08               184
20     2025-09               193
21     2025-10               208
22     2025-11                81

In [537]:
import plotly.express as px

fig = px.line(
    monthly_orders,
    x="order_month",
    y="Number of Orders",
    markers=True,
    title="Monthly Fashion Orders",
    labels={
        "order_month": "Month",
        "Number of Orders": "Orders"
    }
)

fig.update_xaxes(tickangle=45)

fig.show()

### 8. Average Fashion Review Rating by Brand

In [538]:
brand_rating = (
    fashion_sales.groupby("brand", as_index=False)["review_rating"]
    .mean()
    .sort_values(by="review_rating", ascending=False)
    .head(10)
)

brand_rating

      brand  review_rating
5   NeoTech       3.844156
6    Nimbus       3.714286
7     Orion       3.652941
1     Astra       3.577320
2   Everest       3.547486
4    Harbor       3.537037
11   Zenith       3.486301
8     Pulse       3.486111
10   Willow       3.468254
9    Solace       3.449541

In [539]:
fig = px.bar(
    brand_rating,
    x="brand",
    y="review_rating",
    color="review_rating",
    text="review_rating",
    title="Top Fashion Brands by Average Review Rating",
    labels={
        "brand": "Brand",
        "review_rating": "Average Rating"
    }
)

fig.update_traces(texttemplate="%{text:.2f}", textposition="outside")

fig.show()

### 9. Brand Performance by Customer Rating

In [540]:
# Calculate average rating for each brand

brand_rating = (
    fashion_sales
    .groupby("brand")
    .agg(
        average_rating=("product_rating", "mean"),
        total_products=("product_name", "count")
    )
    .sort_values(
        by="average_rating",
        ascending=False
    )
    .head(10)
    .reset_index()
)

brand_rating

       brand  average_rating  total_products
0       Acme        4.098006             341
1      Pulse        4.045851             241
2    Everest        3.972990             485
3     Harbor        3.899353             603
4  GreenLeaf        3.823302             530
5    NeoTech        3.690320             375
6      Orion        3.628498             486
7     Solace        3.573035             346
8     Willow        3.508415             328
9     Zenith        3.391580             386

In [541]:
import plotly.express as px

fig = px.bar(
    brand_rating,
    x="brand",
    y="average_rating",
    title="Top 10 Brands by Customer Rating",
    labels={
        "brand": "Fashion Brand",
        "average_rating": "Average Rating"
    },
    text="average_rating"
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside"
)

fig.show()

### 10.Product Sales by Price Range

In [542]:
# Create price ranges

fashion_sales["price_range"] = pd.cut(
    fashion_sales["price"],
    bins=[0, 50, 200, 500, float("inf")],
    labels=[
        "Budget ($0-$50)",
        "Mid Range ($50-$200)",
        "Premium ($200-$500)",
        "Luxury ($500+)"
    ]
)


# Analyze sales by price range

price_range_analysis = (
    fashion_sales
    .groupby("price_range", observed=True)
    .agg(
        total_products_sold=("quantity", "sum"),
        total_revenue=("item_total", "sum")
    )
    .reset_index()
)


price_range_analysis

            price_range  total_products_sold  total_revenue
0       Budget ($0-$50)                 1398       41133.19
1  Mid Range ($50-$200)                 4282      494809.52
2   Premium ($200-$500)                  732      175373.15

In [543]:
fig = px.bar(
    price_range_analysis,
    x="price_range",
    y="total_revenue",
    title="Fashion Sales Performance by Price Range",
    labels={
        "price_range": "Price Segment",
        "total_revenue": "Revenue ($)"
    },
    text="total_revenue"
)

fig.update_traces(
    texttemplate="%{text:.2s}",
    textposition="outside"
)

fig.show()

### 11. Average Fashion Order Value (KPI)

In [544]:
average_order_value = (
    fashion_sales.groupby("order_id")["item_total"]
    .sum()
    .mean()
)

print(f"Average Fashion Order Value: ${average_order_value:.2f}")

Average Fashion Order Value: $171.32

In [545]:
fashion_sales["brand"].value_counts()

brand
Harbor       603
GreenLeaf    530
Orion        486
Everest      485
Zenith       386
NeoTech      375
Solace       346
Acme         341
Willow       328
Astra        317
Pulse        241
Nimbus       167
Name: count, dtype: int64

In [546]:
fashion_sales["gender"].value_counts()

gender
Other     1582
Female    1551
Male      1472
Name: count, dtype: int64

In [547]:
fashion_sales[["brand", "gender", "city"]].head(20)

         brand  gender                city
13      Nimbus  Female     New Barbarafurt
18      Harbor   Other          Danielfort
24       Astra    Male         Howardmouth
27       Orion   Other         South Peggy
31      Nimbus   Other         New Timothy
43      Harbor  Female         Larsonmouth
48      Solace    Male          East Kelly
61       Astra    Male         Nicholefort
75      Harbor    Male  Christopherchester
85        Acme   Other         Theresastad
90      Willow   Other     Port Jerrymouth
118    Everest    Male        Francisville
140      Orion  Female        Jesuschester
159    Everest    Male           Burnsbury
164     Willow    Male   North Jonathanton
165      Astra  Female            Kingfort
182  GreenLeaf    Male          Scottmouth
190    NeoTech    Male        Rebeccamouth
209  GreenLeaf   Other      East Emilyview
211    NeoTech   Other          Russellton

In [548]:
fashion_sales.columns.tolist()

['order_id',
 'user_id',
 'order_date',
 'order_status',
 'total_amount',
 'name',
 'email',
 'gender',
 'city',
 'signup_date',
 'order_item_id',
 'product_id',
 'quantity',
 'item_price',
 'item_total',
 'product_name',
 'category',
 'brand',
 'price',
 'product_rating',
 'review_rating',
 'review_text',
 'order_month',
 'price_range']

In [549]:
products["category"].unique()

<ArrowStringArray>
[      'Clothing',      'Groceries',         'Sports',    'Electronics',
 'Home & Kitchen',           'Toys',   'Pet Supplies',          'Books',
     'Automotive',         'Beauty']
Length: 10, dtype: str

In [550]:
products["category"].value_counts()

category
Clothing          213
Toys              213
Pet Supplies      212
Beauty            207
Electronics       203
Home & Kitchen    199
Books             194
Automotive        193
Groceries         183
Sports            183
Name: count, dtype: int64

In [551]:
fashion_categories = [
    "Clothing",
    "Shoes",
    "Accessories"
]

fashion_products = products[
    products["category"].isin(fashion_categories)
]

In [552]:
fashion_products["category"].value_counts()

category
Clothing    213
Name: count, dtype: int64

In [553]:
fashion_sales["user_id"].nunique()

3377

In [554]:
fashion_sales["product_id"].nunique()

213

In [555]:
fashion_sales["order_id"].nunique()

4152

In [556]:
fashion_sales["review_text"].count()

np.int64(1611)

In [557]:
print("Users:", fashion_sales["user_id"].nunique())

print("Products:", fashion_sales["product_id"].nunique())

print("Orders:", fashion_sales["order_id"].nunique())

print("Reviews:", fashion_sales["review_text"].count())

Users: 3377
Products: 213
Orders: 4152
Reviews: 1611

In [558]:
fashion_sales["product_name"].head(20)

13        Nimbus When
18       Harbor Night
24      Astra Without
27         Orion Most
31         Nimbus Sit
43        Harbor Beat
48         Solace Car
61         Astra Test
75       Harbor Night
85         Acme Wrong
90        Willow Site
118      Everest Drug
140        Orion Side
159    Everest Single
164     Willow Remain
165        Astra Tend
182    GreenLeaf Wall
190    NeoTech Nearly
209     GreenLeaf Act
211    NeoTech Decide
Name: product_name, dtype: str

In [559]:
fashion_sales.columns

Index(['order_id', 'user_id', 'order_date', 'order_status', 'total_amount',
       'name', 'email', 'gender', 'city', 'signup_date', 'order_item_id',
       'product_id', 'quantity', 'item_price', 'item_total', 'product_name',
       'category', 'brand', 'price', 'product_rating', 'review_rating',
       'review_text', 'order_month', 'price_range'],
      dtype='str')

In [560]:
fashion_sales["category"].unique()

<ArrowStringArray>
['Clothing']
Length: 1, dtype: str

In [561]:
fashion_sales["category"].value_counts()

category
Clothing    4605
Name: count, dtype: int64

# Feature engineering 
Feature engineering is the process of creating new features from existing data to improve machine learning models and recommendation systems.

Since the original fashion sales dataset contains only the Clothing category, a new feature called **subcategory** is added to represent different clothing product types. This enables the AI recommendation system to provide more personalized clothing recommendations.

In [562]:
import numpy as np

In [563]:
np.random.seed(42)

In [564]:
subcategories = [
    "T-Shirt",
    "Shirt",
    "Jeans",
    "Jacket",
    "Hoodie",
    "Dress",
    "Sweater",
    "Shorts",
    "Skirt",
    "Tracksuit"
]

In [565]:
weights = [
    0.20,   # T-Shirt
    0.15,   # Shirt
    0.15,   # Jeans
    0.10,   # Jacket
    0.10,   # Hoodie
    0.10,   # Dress
    0.08,   # Sweater
    0.05,   # Shorts
    0.04,   # Skirt
    0.03    # Tracksuit
]

In [566]:
fashion_sales["subcategory"] = np.random.choice(
    subcategories,
    size=len(fashion_sales),
    p=weights
)

In [567]:
fashion_sales.head()

,order_id,user_id,order_date,order_status,total_amount,name,email,gender,city,signup_date,...,product_name,category,brand,price,product_rating,review_rating,review_text,order_month,price_range,subcategory
13,O00000004,U008986,2025-10-04 20:35:22,cancelled,689.50,Kurt Howard,nancy40@example.org,Female,New Barbarafurt,2024-12-04,...,Nimbus When,Clothing,Nimbus,67.54,3.58,NaN,NaN,2025-10,Mid Range ($50-$200),Jeans
18,O00000006,U003449,2024-10-13 09:02:27,completed,2258.34,Mason Owens,wharris@example.org,Other,Danielfort,2025-05-17,...,Harbor Night,Clothing,Harbor,209.10,3.68,NaN,NaN,2024-10,Premium ($200-$500),Skirt
24,O00000009,U000610,2025-10-29 07:00:11,cancelled,229.02,Rachel Taylor,parkerrichard@example.org,Male,Howardmouth,2025-05-15,...,Astra Without,Clothing,Astra,114.51,2.87,NaN,NaN,2025-10,Mid Range ($50-$200),Dress
27,O00000011,U004470,2025-08-14 09:59:55,shipped,1016.61,Morgan Lopez,michael10@example.com,Other,South Peggy,2025-10-14,...,Orion Most,Clothing,Orion,151.39,3.99,NaN,NaN,2025-08,Mid Range ($50-$200),Jacket
31,O00000012,U009480,2025-08-27 09:57:49,cancelled,600.23,Gabrielle Serrano,rachelblackwell@example.net,Other,New Timothy,2025-01-31,...,Nimbus Sit,Clothing,Nimbus,37.65,4.54,NaN,NaN,2025-08,Budget ($0-$50),T-Shirt

In [568]:
fashion_sales["subcategory"].value_counts()

subcategory
T-Shirt      946
Shirt        677
Jeans        673
Hoodie       499
Jacket       468
Dress        433
Sweater      381
Shorts       203
Skirt        197
Tracksuit    128
Name: count, dtype: int64

In [569]:
import plotly.express as px

subcategory_count = (
    fashion_sales["subcategory"]
    .value_counts()
    .reset_index()
)

subcategory_count.columns = ["Subcategory", "Count"]

fig = px.bar(
    subcategory_count,
    x="Subcategory",
    y="Count",
    color="Count",
    title="Distribution of Clothing Subcategories"
)

fig.show()

In [570]:
fashion_sales.to_csv(
    "fashion_sales.csv",
    index=False
)

### EDA for the new column.

### Distribution of Subcategories

In [571]:
fashion_sales["subcategory"].value_counts()

subcategory
T-Shirt      946
Shirt        677
Jeans        673
Hoodie       499
Jacket       468
Dress        433
Sweater      381
Shorts       203
Skirt        197
Tracksuit    128
Name: count, dtype: int64

### Percentage of Each Subcategory

In [572]:
fashion_sales["subcategory"].value_counts(normalize=True) * 100

subcategory
T-Shirt      20.542888
Shirt        14.701412
Jeans        14.614549
Hoodie       10.836048
Jacket       10.162866
Dress         9.402823
Sweater       8.273616
Shorts        4.408252
Skirt         4.277959
Tracksuit     2.779587
Name: proportion, dtype: float64

### Visualize Subcategory Distribution

In [585]:
import plotly.express as px

subcategory_count = (
    fashion_sales["subcategory"]
    .value_counts()
    .reset_index()
)

subcategory_count.columns = ["Subcategory", "Count"]

fig = px.bar(
    subcategory_count,
    x="Subcategory",
    y="Count",
    color="Count",
    title="Distribution of Clothing Subcategories"
)

fig.show()

In [583]:
fashion_sales.shape

(4605, 25)

In [588]:
fashion_sales.columns.tolist()

['order_id',
 'user_id',
 'order_date',
 'order_status',
 'total_amount',
 'name',
 'email',
 'gender',
 'city',
 'signup_date',
 'order_item_id',
 'product_id',
 'quantity',
 'item_price',
 'item_total',
 'product_name',
 'category',
 'brand',
 'price',
 'product_rating',
 'review_rating',
 'review_text',
 'order_month',
 'price_range',
 'subcategory']

In [587]:
"order_month" in fashion_sales.columns

True

In [586]:
"price_range" in fashion_sales.columns

True